-- Production schema already applied to Supabase project usa-travel-compliance.
-- Recreate the core schema in a fresh project by executing this file before seed.sql.
create extension if not exists pgcrypto;

create table public.profiles (user_id uuid primary key references auth.users(id) on delete cascade,display_name text,home_country text not null default 'HN',preferred_language text not null default 'es',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.trips (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,origin_country text not null default 'HN',destination_country text not null default 'US',departure_date date not null,return_date date,airline text,flight_number text,booking_reference text,entry_airport text,exit_airport text,purpose text,status text not null default 'planned' check(status in('planned','active','completed','cancelled')),admit_until date,i94_admission_class text,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(return_date is null or return_date>=departure_date));
create table public.trip_bags (id uuid primary key default gen_random_uuid(),trip_id uuid not null references public.trips(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,bag_type text not null check(bag_type in('personal_item','carry_on','checked')),label text not null,weight_kg numeric(6,2),created_at timestamptz not null default now());
create table public.regulatory_sources (id uuid primary key default gen_random_uuid(),agency text not null,title text not null,url text not null,jurisdiction text not null default 'US',effective_from date,effective_to date,last_verified_at timestamptz not null default now(),source_hash text,unique(agency,url));
create table public.catalog_items (id uuid primary key default gen_random_uuid(),canonical_name_es text not null,canonical_name_en text not null,category text not null,subcategory text,scientific_name text,default_risk text not null default 'review' check(default_risk in('low','medium','high','review')),aliases text[] not null default '{}',active boolean not null default true,created_at timestamptz not null default now(),unique(canonical_name_es,category));
create table public.regulatory_rules (id uuid primary key default gen_random_uuid(),source_id uuid not null references public.regulatory_sources(id) on delete restrict,catalog_item_id uuid references public.catalog_items(id) on delete cascade,origin_country text,destination_region text not null default 'US_CONTINENTAL',condition_json jsonb not null default '{}'::jsonb,decision text not null check(decision in('allowed','allowed_declare','restricted','prohibited','review')),risk_level text not null check(risk_level in('low','medium','high','review')),declaration_required boolean not null default true,traveler_action text not null,explanation text not null,rule_version text not null,effective_from date not null,effective_to date,last_verified_at timestamptz not null default now(),active boolean not null default true);
create table public.trip_items (id uuid primary key default gen_random_uuid(),trip_id uuid not null references public.trips(id) on delete cascade,bag_id uuid references public.trip_bags(id) on delete set null,user_id uuid not null references auth.users(id) on delete cascade,catalog_item_id uuid references public.catalog_items(id) on delete set null,custom_name text,quantity numeric(10,2) not null default 1,unit text not null default 'unit',homemade boolean,cooked_state text check(cooked_state is null or cooked_state in('raw','partially_cooked','fully_cooked','processed','not_applicable')),commercial_packaging boolean,hermetically_sealed boolean,shelf_stable boolean,contains_meat boolean,declared boolean not null default false,computed_decision text not null default 'review' check(computed_decision in('allowed','allowed_declare','restricted','prohibited','review')),computed_risk text not null default 'review' check(computed_risk in('low','medium','high','review')),matched_rule_id uuid references public.regulatory_rules(id) on delete set null,rule_version text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(catalog_item_id is not null or custom_name is not null));
create table public.trip_documents (id uuid primary key default gen_random_uuid(),trip_id uuid references public.trips(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,document_type text not null check(document_type in('passport','visa','i94','ticket','hotel','insurance','other')),storage_path text,masked_identifier text,issued_on date,expires_on date,created_at timestamptz not null default now());
create table public.inspections (id uuid primary key default gen_random_uuid(),trip_id uuid not null references public.trips(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,inspection_type text not null check(inspection_type in('cbp_primary','cbp_secondary','agriculture','tsa','other')),occurred_at timestamptz not null default now(),item_confiscated boolean not null default false,warning_received boolean not null default false,fine_amount_usd numeric(10,2) not null default 0,notes text);
create table public.compliance_snapshots (id uuid primary key default gen_random_uuid(),trip_id uuid not null references public.trips(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,document_score smallint not null check(document_score between 0 and 100),stay_score smallint not null check(stay_score between 0 and 100),cbp_score smallint not null check(cbp_score between 0 and 100),usda_score smallint not null check(usda_score between 0 and 100),tsa_score smallint not null check(tsa_score between 0 and 100),readiness_score smallint not null check(readiness_score between 0 and 100),blockers jsonb not null default '[]'::jsonb,created_at timestamptz not null default now());

create index trips_user_date_idx on public.trips(user_id,departure_date desc);create index trip_items_trip_idx on public.trip_items(trip_id);create index trip_bags_trip_idx on public.trip_bags(trip_id);create index regulatory_rules_lookup_idx on public.regulatory_rules(catalog_item_id,origin_country,destination_region,active);create index catalog_items_aliases_idx on public.catalog_items using gin(aliases);create index compliance_snapshots_trip_idx on public.compliance_snapshots(trip_id);create index compliance_snapshots_user_idx on public.compliance_snapshots(user_id);create index inspections_trip_idx on public.inspections(trip_id);create index inspections_user_idx on public.inspections(user_id);create index regulatory_rules_source_idx on public.regulatory_rules(source_id);create index trip_bags_user_idx on public.trip_bags(user_id);create index trip_documents_trip_idx on public.trip_documents(trip_id);create index trip_documents_user_idx on public.trip_documents(user_id);create index trip_items_bag_idx on public.trip_items(bag_id);create index trip_items_catalog_idx on public.trip_items(catalog_item_id);create index trip_items_rule_idx on public.trip_items(matched_rule_id);create index trip_items_user_idx on public.trip_items(user_id);

alter table public.profiles enable row level security;alter table public.trips enable row level security;alter table public.trip_bags enable row level security;alter table public.trip_items enable row level security;alter table public.trip_documents enable row level security;alter table public.inspections enable row level security;alter table public.compliance_snapshots enable row level security;alter table public.catalog_items enable row level security;alter table public.regulatory_sources enable row level security;alter table public.regulatory_rules enable row level security;
create policy profiles_own_select on public.profiles for select to authenticated using((select auth.uid())=user_id);create policy profiles_own_insert on public.profiles for insert to authenticated with check((select auth.uid())=user_id);create policy profiles_own_update on public.profiles for update to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);create policy trips_own_all on public.trips for all to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);create policy trip_bags_own_all on public.trip_bags for all to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);create policy trip_items_own_all on public.trip_items for all to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);create policy trip_documents_own_all on public.trip_documents for all to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);create policy inspections_own_all on public.inspections for all to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);create policy compliance_snapshots_own_all on public.compliance_snapshots for all to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);create policy catalog_authenticated_read on public.catalog_items for select to authenticated using(active=true);create policy sources_authenticated_read on public.regulatory_sources for select to authenticated using(true);create policy rules_authenticated_read on public.regulatory_rules for select to authenticated using(active=true and(effective_to is null or effective_to>=current_date));
grant usage on schema public to authenticated;grant select,insert,update,delete on public.profiles,public.trips,public.trip_bags,public.trip_items,public.trip_documents,public.inspections,public.compliance_snapshots to authenticated;grant select on public.catalog_items,public.regulatory_sources,public.regulatory_rules to authenticated;

create or replace function public.set_updated_at() returns trigger language plpgsql security invoker set search_path=public as $$begin new.updated_at=now();return new;end;$$;
create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();create trigger trips_set_updated_at before update on public.trips for each row execute function public.set_updated_at();create trigger trip_items_set_updated_at before update on public.trip_items for each row execute function public.set_updated_at();
insert into storage.buckets(id,name,public) values('travel-documents','travel-documents',false) on conflict(id) do nothing;
create policy travel_documents_insert_own on storage.objects for insert to authenticated with check(bucket_id='travel-documents' and(storage.foldername(name))[1]=(select auth.uid())::text);create policy travel_documents_select_own on storage.objects for select to authenticated using(bucket_id='travel-documents' and(storage.foldername(name))[1]=(select auth.uid())::text);create policy travel_documents_update_own on storage.objects for update to authenticated using(bucket_id='travel-documents' and(storage.foldername(name))[1]=(select auth.uid())::text) with check(bucket_id='travel-documents' and(storage.foldername(name))[1]=(select auth.uid())::text);create policy travel_documents_delete_own on storage.objects for delete to authenticated using(bucket_id='travel-documents' and(storage.foldername(name))[1]=(select auth.uid())::text);
