import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

type Obj=Record<string,any>;
type Presentation={count:number;size:number;unit:string};
type InputItem={catalogKey:string;name:string;profileKey:string;measurementKind?:string;quantityValue?:number;quantityUnit?:string;presentations?:Presentation[];abvPercent?:number;batteryWh?:number;batteryMah?:number;batteryVoltage?:number;daysSupply?:number};
const VERSION="3.1.0-20260830";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type, x-client-info","Access-Control-Allow-Methods":"POST, OPTIONS"};

const SOURCES:Record<string,Obj>={
 APHIS_GENERAL:{agency:"USDA-APHIS",title:"Traveling From Another Country",url:"https://www.aphis.usda.gov/traveling-with-ag-products/another-country",verified:"2026-03-31"},
 APHIS_MEAT:{agency:"USDA-APHIS",title:"Meats, Poultry, and Seafood",url:"https://www.aphis.usda.gov/traveling-with-ag-products/meats-poultry-seafood",verified:"2026-01-13"},
 APHIS_DAIRY:{agency:"USDA-APHIS",title:"Milk, Dairy, and Egg Products",url:"https://www.aphis.usda.gov/traveling-with-ag-products/milk-dairy-eggs",verified:"2026-01-13"},
 APHIS_PRODUCE:{agency:"USDA-APHIS",title:"Fruits and Vegetables",url:"https://www.aphis.usda.gov/traveling-with-ag-products/fruits-vegetables",verified:"2026-01-13"},
 APHIS_PANTRY:{agency:"USDA-APHIS",title:"Coffee, Teas, Honey, Nuts, and Spices",url:"https://www.aphis.usda.gov/traveling-with-ag-products/coffee-tea-honey-nuts-spices",verified:"2026-01-13"},
 APHIS_PLANTS:{agency:"USDA-APHIS",title:"Plants, Plant Parts, Cut Flowers, and Seeds",url:"https://www.aphis.usda.gov/traveling-with-ag-products/plants-plant-parts",verified:"2026-02-24"},
 APHIS_SOIL:{agency:"USDA-APHIS",title:"Soil and Soil-Related Products",url:"https://www.aphis.usda.gov/traveling-with-ag-products/soil",verified:"2026-01-13"},
 APHIS_SOUVENIRS:{agency:"USDA-APHIS",title:"Souvenirs",url:"https://www.aphis.usda.gov/traveling-with-ag-products/souvenirs",verified:"2026-01-13"},
 APHIS_HEALTH:{agency:"USDA-APHIS",title:"Region Health Status - Animals",url:"https://www.aphis.usda.gov/regionalization-evaluation-services/region-health-status",verified:"2026-08-30"},
 ACIR:{agency:"USDA-APHIS",title:"Agricultural Commodity Import Requirements",url:"https://acir.aphis.usda.gov/",verified:"2026-08-30"},
 CBP_DECLARE:{agency:"CBP",title:"Articles to Declare",url:"https://www.help.cbp.gov/s/article/Article-1909?language=es",verified:"2026-02-13"},
 CBP_ALCOHOL:{agency:"CBP",title:"Alcohol for Personal Use",url:"https://www.help.cbp.gov/s/article/Article-1395?language=en_US",verified:"2026-02-13"},
 CBP_DUTY:{agency:"CBP",title:"Customs Duty Information",url:"https://www.cbp.gov/travel/international-visitors/know-before-you-visit/customs-duty-information",verified:"2026-08-30"},
 CBP_CURRENCY:{agency:"CBP",title:"Currency and Monetary Instruments",url:"https://www.help.cbp.gov/s/article/Article-1393?language=en_US",verified:"2026-03-29"},
 CBP_TOBACCO:{agency:"CBP",title:"Tobacco Products for Personal Use",url:"https://www.help.cbp.gov/s/article/Article-1376?language=en_US",verified:"2026-04-22"},
 TSA_ALL:{agency:"TSA",title:"What Can I Bring?",url:"https://www.tsa.gov/travel/security-screening/whatcanibring/all-list",verified:"2026-08-30"},
 TSA_ALCOHOL:{agency:"TSA",title:"Alcoholic Beverages",url:"https://www.tsa.gov/travel/security-screening/whatcanibring/items/alcoholic-beverages",verified:"2026-08-30"},
 TSA_TIPS:{agency:"TSA",title:"TSA Travel Tips / 3-1-1",url:"https://www.tsa.gov/news/press/factsheets/tsa-travel-tips",verified:"2026-08-30"},
 FAA_PACKSAFE:{agency:"FAA",title:"PackSafe for Passengers",url:"https://www.faa.gov/hazmat/packsafe",verified:"2026-08-30"},
 FAA_ALCOHOL:{agency:"FAA",title:"PackSafe - Alcoholic Beverages",url:"https://www.faa.gov/hazmat/packsafe/alcoholic-beverages",verified:"2026-04-13"},
 FAA_BATTERIES:{agency:"FAA",title:"PackSafe - Batteries",url:"https://www.faa.gov/hazmat/packsafe/batteries",verified:"2026-08-30"},
 FAA_TOILETRIES:{agency:"FAA",title:"PackSafe - Medicinal & Toiletry Articles",url:"https://www.faa.gov/hazmat/packsafe/medicinal-toiletry-articles",verified:"2026-08-30"},
 FAA_DRY_ICE:{agency:"FAA",title:"PackSafe - Dry Ice",url:"https://www.faa.gov/hazmat/packsafe/dry-ice",verified:"2026-08-30"},
 FAA_LIGHTERS:{agency:"FAA",title:"PackSafe - Lighters",url:"https://www.faa.gov/hazmat/packsafe/lighters",verified:"2026-08-30"},
 FAA_VAPE:{agency:"FAA",title:"PackSafe - Electronic Cigarettes, Vaping Devices",url:"https://www.faa.gov/hazmat/packsafe/e-cigarettes-vaping",verified:"2026-08-30"},
 FAA_OXYGEN:{agency:"FAA",title:"PackSafe - Oxygen",url:"https://www.faa.gov/hazmat/packsafe/oxygen-compressed-or-liquid",verified:"2026-08-30"},
 FDA_PERSONAL:{agency:"FDA",title:"Personal Importation",url:"https://www.fda.gov/importeddrugs",verified:"2026-08-30"},
 FDA_MEDS:{agency:"FDA",title:"Traveling with Prescription Medications",url:"https://www.fda.gov/drugs/fda-drug-info-rounds-video/traveling-prescription-medications",verified:"2026-08-30"},
 FWS_IMPORT:{agency:"USFWS",title:"Information for Importers & Exporters",url:"https://www.fws.gov/program/office-of-law-enforcement/information-importers-exporters",verified:"2026-08-30"}
};

type Profile={decision:string;declare:boolean;bag:string;sources:string[];requirements:string[];age21?:boolean};
const P:Record<string,Profile>={
 ordinary:{decision:"allowed",declare:false,bag:"either",sources:["TSA_ALL"],requirements:["Sujeto a la decisión final de TSA y a la política de la aerolínea."]},
 tsa_liquid:{decision:"allowed",declare:false,bag:"checked_if_over_100ml",sources:["TSA_TIPS","TSA_ALL"],requirements:["En carry-on, cada envase normalmente debe ser de 100 ml (3.4 fl oz) o menos."]},
 tsa_medical_liquid:{decision:"allowed",declare:false,bag:"carry_on",sources:["TSA_TIPS"],requirements:["Los líquidos médicamente necesarios pueden superar 100 ml; deben presentarse para inspección separada en seguridad."]},
 toiletry_liquid:{decision:"allowed",declare:false,bag:"checked_if_over_100ml",sources:["FAA_TOILETRIES","TSA_TIPS"],requirements:["Máximo agregado FAA de la excepción: 2 L o 2 kg por persona.","Máximo por envase bajo esta excepción: 500 ml o 0.5 kg.","En carry-on, cada envase normalmente debe ser de 100 ml o menos."]},
 toiletry_aerosol:{decision:"allowed",declare:false,bag:"checked_if_over_100ml",sources:["FAA_TOILETRIES","TSA_TIPS"],requirements:["Cuenta dentro del máximo agregado de 2 L o 2 kg.","Máximo por envase: 500 ml o 0.5 kg.","Protege la boquilla contra liberación accidental."]},
 alcohol_under24:{decision:"allowed_declare",declare:true,bag:"checked_if_over_100ml",age21:true,sources:["CBP_ALCOHOL","CBP_DUTY","TSA_ALCOHOL","FAA_ALCOHOL"],requirements:["Edad mínima: 21 años.","La referencia federal general de franquicia es 1 L; el excedente se declara y puede pagar arancel/impuesto.","En carry-on, cada envase debe ser de 100 ml o menos salvo excepciones aplicables.","La ley del estado de entrada puede ser más restrictiva."]},
 alcohol_24_70:{decision:"allowed_declare",declare:true,bag:"checked_if_over_100ml",age21:true,sources:["CBP_ALCOHOL","CBP_DUTY","TSA_ALCOHOL","FAA_ALCOHOL"],requirements:["Edad mínima: 21 años.","Máximo FAA: 5 L totales por pasajero para bebidas de más de 24% y hasta 70% ABV.","Debe permanecer en empaque minorista sin abrir.","En carry-on, cada envase debe ser de 100 ml o menos salvo excepciones aplicables.","La referencia federal general de franquicia es 1 L; el excedente se declara y puede pagar arancel/impuesto.","La ley del estado de entrada puede ser más restrictiva."]},
 alcohol_over70:{decision:"prohibited",declare:true,bag:"none",age21:true,sources:["TSA_ALCOHOL","FAA_ALCOHOL"],requirements:["Bebidas con más de 70% ABV no están permitidas en equipaje de pasajeros."]},
 coffee_roasted:{decision:"allowed_declare",declare:true,bag:"either",sources:["APHIS_PANTRY","CBP_DECLARE"],requirements:["USDA permite cantidades ilimitadas de café tostado en equipaje.","Debe declararse al entrar."]},
 coffee_green:{decision:"allowed_declare",declare:true,bag:"either",sources:["APHIS_PANTRY","CBP_DECLARE"],requirements:["Permitido en cantidades ilimitadas hacia Estados Unidos continental.","No aplica igual para Hawaii o Puerto Rico.","Debe declararse."]},
 coffee_cherry:{decision:"prohibited",declare:true,bag:"none",sources:["APHIS_PANTRY"],requirements:["La cereza fresca de café está prohibida en todos los puertos de entrada."]},
 fruit_fresh:{decision:"review",declare:true,bag:"conditional",sources:["APHIS_PRODUCE","ACIR"],requirements:["APHIS indica que casi todas las frutas frescas están prohibidas, pero existen excepciones específicas por mercancía y origen; debe resolverse en ACIR."]},
 vegetable_fresh:{decision:"review",declare:true,bag:"conditional",sources:["APHIS_PRODUCE","ACIR"],requirements:["APHIS indica que casi todos los vegetales frescos están prohibidos, pero existen excepciones específicas por mercancía y origen; debe resolverse en ACIR."]},
 produce_frozen:{decision:"review",declare:true,bag:"conditional",sources:["APHIS_PRODUCE","ACIR"],requirements:["APHIS indica que casi todas las frutas y vegetales congelados están prohibidos; se requiere revisión específica para evitar falsos resultados."]},
 produce_canned_commercial:{decision:"allowed_declare",declare:true,bag:"either",sources:["APHIS_PRODUCE","CBP_DECLARE"],requirements:["Las frutas y vegetales comercialmente enlatados pueden ingresar si se declaran."]},
 produce_home_canned:{decision:"prohibited",declare:true,bag:"none",sources:["APHIS_PRODUCE"],requirements:["APHIS no permite conservas caseras de frutas o vegetales."]},
 produce_dried:{decision:"review",declare:true,bag:"conditional",sources:["APHIS_PRODUCE","ACIR"],requirements:["Los productos secos dependen de la mercancía específica; algunos están permitidos y otros requieren restricciones adicionales."]},
 spices_dried:{decision:"allowed_declare",declare:true,bag:"either",sources:["APHIS_PANTRY","CBP_DECLARE"],requirements:["La mayoría de especias secas pueden importarse, con excepciones específicas.","Debe declararse."]},
 nuts_roasted:{decision:"allowed_declare",declare:true,bag:"either",sources:["APHIS_PANTRY","CBP_DECLARE"],requirements:["Las nueces cocidas o tostadas están permitidas.","Debe declararse."]},
 honey:{decision:"allowed_declare",declare:true,bag:"either",sources:["APHIS_PANTRY","CBP_DECLARE"],requirements:["Generalmente permitido para consumo personal.","Debe declararse."]},
 seed_food:{decision:"review",declare:true,bag:"conditional",sources:["APHIS_PANTRY","ACIR"],requirements:["Semillas y granos pueden tener restricciones fitosanitarias; requiere resolución específica cuando no hay regla directa."]},
 dry_food:{decision:"allowed_declare",declare:true,bag:"either",sources:["APHIS_GENERAL","CBP_DECLARE"],requirements:["Declara los alimentos y productos agrícolas; la decisión final corresponde a CBP/USDA."]},
 baked_goods:{decision:"allowed_declare",declare:true,bag:"either",sources:["APHIS_GENERAL","APHIS_DAIRY","CBP_DECLARE"],requirements:["Declara el alimento; si contiene carne, huevo no completamente cocido u otro ingrediente restringido puede aplicar una regla más estricta."]},
 prepared_mixed:{decision:"review",declare:true,bag:"conditional",sources:["APHIS_GENERAL","APHIS_MEAT","APHIS_DAIRY","APHIS_PRODUCE","CBP_DECLARE"],requirements:["La decisión depende de los ingredientes; no se autoriza automáticamente una comida mixta sin evidencia suficiente."]},
 poultry_cooked:{decision:"allowed_declare",declare:true,bag:"either",sources:["APHIS_MEAT","APHIS_HEALTH","CBP_DECLARE"],requirements:["Debe estar completamente cocido en toda su extensión.","Debe declararse y puede ser inspeccionado.","APHIS limita el equipaje personal a no más de 50 lb de un artículo antes de tratarlo como envío comercial."]},
 poultry_raw:{decision:"review",declare:true,bag:"conditional",sources:["APHIS_MEAT","APHIS_HEALTH"],requirements:["La admisibilidad depende del estado sanitario vigente del país de origen para HPAI/Newcastle."]},
 poultry_shelf_stable:{decision:"allowed_declare",declare:true,bag:"either",sources:["APHIS_MEAT","CBP_DECLARE"],requirements:["Debe ser comercial, etiquetado, cocido, shelf-stable y estar sin abrir.","Máximo de equipaje personal: 50 lb por artículo."]},
 pork_general:{decision:"review",declare:true,bag:"conditional",sources:["APHIS_MEAT","APHIS_HEALTH"],requirements:["La admisibilidad depende del estado sanitario vigente del país de origen y del procesamiento.","Debe declararse."]},
 pork_processed:{decision:"review",declare:true,bag:"conditional",sources:["APHIS_MEAT","APHIS_HEALTH"],requirements:["Productos de cerdo están sujetos a restricciones de sanidad animal según origen y preparación."]},
 ruminant_meat:{decision:"review",declare:true,bag:"conditional",sources:["APHIS_MEAT","APHIS_HEALTH"],requirements:["La admisibilidad depende del estado sanitario del país de origen para enfermedades animales relevantes."]},
 dairy:{decision:"review",declare:true,bag:"either",sources:["APHIS_DAIRY","APHIS_HEALTH","CBP_DECLARE"],requirements:["Mantequilla y quesos sólidos sin carne que no sean líquidos pueden ingresar desde cualquier país.","Otros lácteos dependen del estatus sanitario y del procesamiento."]},
 dairy_processed:{decision:"allowed_declare",declare:true,bag:"either",sources:["APHIS_DAIRY","CBP_DECLARE"],requirements:["Productos con leche seca correctamente etiquetados y ciertos alimentos comerciales shelf-stable sin abrir tienen excepciones."]},
 egg_product:{decision:"review",declare:true,bag:"conditional",sources:["APHIS_DAIRY","APHIS_HEALTH","CBP_DECLARE"],requirements:["La admisibilidad depende de HPAI/Newcastle; productos completamente cocidos pueden ser admitidos tras inspección."]},
 seafood:{decision:"review",declare:true,bag:"either",sources:["APHIS_MEAT","FDA_PERSONAL","FWS_IMPORT","CBP_DECLARE"],requirements:["APHIS no regula la mayoría de mariscos; FDA/USFWS pueden aplicar según especie o producto."]},
 seafood_breaded:{decision:"review",declare:true,bag:"either",sources:["APHIS_MEAT","FDA_PERSONAL"],requirements:["APHIS regula mariscos empanizados cuando el empanizado contiene ingredientes de origen animal como leche o huevo."]},
 plant_material:{decision:"review",declare:true,bag:"conditional",sources:["APHIS_PLANTS","ACIR","CBP_DECLARE"],requirements:["Puede requerir permiso, certificado o inspección; consulta ACIR por mercancía específica."]},
 plant_seed:{decision:"review",declare:true,bag:"conditional",sources:["APHIS_PLANTS","ACIR","CBP_DECLARE"],requirements:["Semillas para propagación pueden requerir certificado fitosanitario, permiso o estar prohibidas."]},
 soil:{decision:"prohibited",declare:true,bag:"none",sources:["APHIS_SOIL","CBP_DECLARE"],requirements:["El suelo extranjero está fuertemente restringido y generalmente requiere permiso/tratamiento; no debe empacarse como artículo personal ordinario."]},
 plant_souvenir:{decision:"review",declare:true,bag:"conditional",sources:["APHIS_SOUVENIRS","ACIR","CBP_DECLARE"],requirements:["Madera, palma, bambú u otros materiales vegetales pueden requerir inspección o restricciones."]},
 wildlife_souvenir:{decision:"review",declare:true,bag:"conditional",sources:["FWS_IMPORT","APHIS_SOUVENIRS","CBP_DECLARE"],requirements:["Productos de fauna pueden estar sujetos a USFWS/CITES y requieren revisión por especie/material."]},
 lithium_device:{decision:"allowed",declare:false,bag:"carry_on_preferred",sources:["FAA_BATTERIES","TSA_ALL"],requirements:["Si se factura, el dispositivo debe estar completamente apagado y protegido.","Baterías de repuesto deben ir en carry-on."]},
 power_bank_100:{decision:"allowed",declare:false,bag:"carry_on",sources:["FAA_BATTERIES","TSA_ALL"],requirements:["Debe ir en carry-on o en la persona; no en equipaje facturado.","Proteger terminales contra cortocircuito."]},
 power_bank_160:{decision:"conditional",declare:false,bag:"carry_on",sources:["FAA_BATTERIES","TSA_ALL"],requirements:["Requiere aprobación de la aerolínea.","Máximo dos baterías de repuesto de 101–160 Wh.","Debe ir en carry-on."]},
 battery_over160:{decision:"prohibited",declare:false,bag:"none",sources:["FAA_BATTERIES"],requirements:["Más de 160 Wh no se permite como batería estándar de pasajero."]},
 dry_battery:{decision:"allowed",declare:false,bag:"either",sources:["FAA_BATTERIES"],requirements:["Proteger contra daño y cortocircuito."]},
 medication:{decision:"allowed_declare",declare:true,bag:"carry_on_preferred",sources:["FDA_PERSONAL","FDA_MEDS","CBP_DECLARE"],requirements:["FDA/CBP usan como regla práctica cantidades de uso personal y una referencia de no más de 90 días.","Mantener en envase original y llevar receta/carta médica cuando corresponda."]},
 controlled_medication_review:{decision:"review",declare:true,bag:"carry_on_preferred",sources:["FDA_PERSONAL","FDA_MEDS","CBP_DECLARE"],requirements:["Las sustancias controladas tienen reglas adicionales; requiere revisión específica del medicamento."]},
 medical_device:{decision:"allowed",declare:false,bag:"either",sources:["TSA_ALL","FDA_PERSONAL"],requirements:["Puede requerir inspección; verifica aerolínea para equipos grandes o con baterías."]},
 animal_product_review:{decision:"review",declare:true,bag:"conditional",sources:["APHIS_MEAT","APHIS_HEALTH"],requirements:["Ingredientes de origen animal pueden activar requisitos sanitarios específicos."]},
 cash:{decision:"allowed",declare:false,bag:"either",sources:["CBP_CURRENCY"],requirements:["Es legal transportar cualquier cantidad.","Si el total combinado supera $10,000 USD o equivalente, debes declarar y presentar FinCEN 105."]},
 tobacco_cigarette:{decision:"conditional",declare:true,bag:"either",age21:true,sources:["CBP_TOBACCO","CBP_DECLARE"],requirements:["La exención personal de viajeros elegibles contempla hasta 200 cigarrillos; la elegibilidad depende del estatus del viajero.","Edad mínima 21."]},
 tobacco_cigar:{decision:"conditional",declare:true,bag:"either",age21:true,sources:["CBP_TOBACCO","CBP_DECLARE"],requirements:["La exención personal de viajeros elegibles contempla hasta 100 puros; la elegibilidad depende del estatus del viajero.","Edad mínima 21."]},
 tobacco_other:{decision:"review",declare:true,bag:"conditional",age21:true,sources:["CBP_TOBACCO","CBP_DECLARE"],requirements:["Límites y exenciones dependen del tipo de tabaco y del estatus del viajero.","Edad mínima 21."]},
 checked_only_tool:{decision:"conditional",declare:false,bag:"checked",sources:["TSA_ALL"],requirements:["No debe ir en carry-on; empácalo en equipaje facturado y verifica la aerolínea."]},
 tsa_special:{decision:"review",declare:false,bag:"conditional",sources:["TSA_ALL","FAA_PACKSAFE"],requirements:["Tiene instrucciones específicas TSA/FAA; requiere revisión del artículo concreto."]},
 dry_ice:{decision:"conditional",declare:false,bag:"conditional",sources:["FAA_DRY_ICE","TSA_ALL"],requirements:["Máximo 2.5 kg (5.5 lb) por pasajero y paquete.","Requiere aprobación de la aerolínea.","El empaque debe permitir ventilación de CO2; si se factura debe estar marcado."]},
 vape:{decision:"conditional",declare:false,bag:"carry_on",age21:true,sources:["FAA_VAPE","TSA_ALL"],requirements:["Debe ir en la persona o carry-on, nunca facturado.","Evitar activación accidental y no recargar a bordo.","Cada batería debe cumplir los límites FAA."]},
 lighter:{decision:"conditional",declare:false,bag:"carry_on",sources:["FAA_LIGHTERS","TSA_ALL"],requirements:["Se aplican condiciones específicas FAA/TSA; los encendedores tipo soplete están prohibidos."]},
 oxygen:{decision:"prohibited",declare:false,bag:"none",sources:["FAA_OXYGEN"],requirements:["El pasajero no puede llevar su propio oxígeno comprimido o líquido; coordina servicio con la aerolínea."]}
};

const MASS:Record<string,number>={mg:.001,g:1,kg:1000,oz:28.349523125,lb:453.59237};
const VOL:Record<string,number>={ml:1,L:1000,fl_oz:29.5735295625,cup:236.588,pint:473.176,quart:946.353,gallon:3785.411784};
const num=(v:any,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const unique=<T>(arr:T[])=>[...new Set(arr)];
function totalBase(item:InputItem){const pres=Array.isArray(item.presentations)?item.presentations.filter(x=>num(x.count)>0&&num(x.size)>0):[];if(pres.length){if(item.measurementKind==="mass")return pres.reduce((s,x)=>s+num(x.count)*num(x.size)*(MASS[x.unit]||0),0);if(item.measurementKind==="volume")return pres.reduce((s,x)=>s+num(x.count)*num(x.size)*(VOL[x.unit]||0),0);}if(item.measurementKind==="mass")return num(item.quantityValue,1)*(MASS[item.quantityUnit||"lb"]||1);if(item.measurementKind==="volume")return num(item.quantityValue,1)*(VOL[item.quantityUnit||"ml"]||1);if(item.measurementKind==="days")return num(item.daysSupply||item.quantityValue,1);if(item.measurementKind==="money")return num(item.quantityValue,0);return num(item.quantityValue,1);}
function maxContainerMl(item:InputItem){return Math.max(0,...(item.presentations||[]).map(x=>num(x.size)*(VOL[x.unit]||0)),item.measurementKind==="volume"?num(item.quantityValue)*(VOL[item.quantityUnit||"ml"]||1):0);}
function sourceRows(keys:string[]){return unique(keys).map(k=>({key:k,...SOURCES[k]})).filter(x=>x.url);}
function ageAt(dob:string|null|undefined,onDate:string|null|undefined){if(!dob||!onDate)return null;const d=new Date(`${dob}T12:00:00Z`),t=new Date(`${onDate}T12:00:00Z`);let a=t.getUTCFullYear()-d.getUTCFullYear();const m=t.getUTCMonth()-d.getUTCMonth();if(m<0||(m===0&&t.getUTCDate()<d.getUTCDate()))a--;return a;}

function evaluate(item:InputItem,age:number|null){const p=P[item.profileKey]||P.tsa_special;let decision=p.decision,declare=p.declare,bag=p.bag;const requirements=[...p.requirements];const base=totalBase(item);const name=(item.name||"").toLowerCase();let normalized:Obj={kind:item.measurementKind||"count",value:base,unit:item.measurementKind==="mass"?"g":item.measurementKind==="volume"?"ml":item.measurementKind==="days"?"days":item.measurementKind==="money"?"USD":"count"};
 if(p.age21){if(age!==null&&age<21){decision="prohibited";bag="none";requirements.unshift(`El viajero tendrá ${age} años en la fecha de salida; este artículo requiere 21+.`);}else if(age===null&&decision!=="prohibited"){decision="conditional";requirements.unshift("Registra la fecha de nacimiento en Perfil para verificar automáticamente el requisito de 21+.");}}
 if(item.profileKey==="poultry_cooked"||item.profileKey==="poultry_shelf_stable"){if(base>22679.6185){decision="review";requirements.push("Supera 50 lb de este artículo; APHIS lo trata como envío comercial y exige requisitos adicionales.");}}
 if(item.profileKey==="dairy"){const direct=["mantequilla","queso sólido","quesillo","queso fresco","queso seco","queso crema","mozzarella","cheddar","parmesano","queso rallado"];if(direct.some(x=>name.includes(x))){decision="allowed_declare";requirements.push("APHIS permite mantequilla y quesos sólidos duros o blandos desde cualquier país si no contienen carne y no son líquidos tipo ricotta/cottage.");}}
 if(item.profileKey==="medication"){const days=num(item.daysSupply||item.quantityValue,0);if(days>90){decision="review";requirements.push("Supera la referencia de 90 días para cantidades de uso personal; requiere documentación/revisión adicional.");}}
 if(["power_bank_100","power_bank_160","battery_over160","vape"].includes(item.profileKey)){let wh=num(item.batteryWh,0);if(!wh&&num(item.batteryMah)>0&&num(item.batteryVoltage)>0)wh=num(item.batteryMah)*num(item.batteryVoltage)/1000;normalized={kind:"battery",value:wh,unit:"Wh",count:Math.max(1,num(item.quantityValue,1))};if(wh>160){decision="prohibited";bag="none";requirements.push("La capacidad calculada supera 160 Wh.");}else if(wh>100){decision="conditional";bag="carry_on";requirements.push("Capacidad entre 101 y 160 Wh: requiere aprobación de la aerolínea y se limita a dos repuestos.");}else if(wh>0){decision="allowed";bag="carry_on";}else if(["power_bank_100","power_bank_160","battery_over160"].includes(item.profileKey)){decision="review";requirements.push("Falta capacidad Wh para verificar el límite de batería.");}}
 if(["tsa_liquid","toiletry_liquid","toiletry_aerosol","alcohol_under24","alcohol_24_70"].includes(item.profileKey)&&maxContainerMl(item)>100)bag="checked";
 if(["toiletry_liquid","toiletry_aerosol"].includes(item.profileKey)&&maxContainerMl(item)>500){decision="review";requirements.push("Algún envase supera 500 ml; verifica si el producto está cubierto por otra excepción o debe ir bajo otra regla de transporte.");}
 if(item.profileKey==="dry_ice"&&base>2500){decision="prohibited";bag="none";requirements.push("Supera 2.5 kg (5.5 lb), el máximo FAA por pasajero y paquete.");}
 if(item.profileKey==="cash"&&base>10000){declare=true;decision="allowed_declare";requirements.push("Total superior a $10,000: debes declarar y presentar FinCEN Form 105.");}
 return {catalogKey:item.catalogKey,name:item.name,profileKey:item.profileKey,decision,declarationRequired:declare,recommendedBag:bag,requirements:unique(requirements),normalized,sources:sourceRows(p.sources),presentations:item.presentations||[],input:item};}

function aggregate(evals:any[]){const checks:any[]=[];const volume=(profiles:string[])=>evals.filter(e=>profiles.includes(e.profileKey)&&e.normalized.unit==="ml").reduce((s,e)=>s+num(e.normalized.value),0);const mass=(profiles:string[])=>evals.filter(e=>profiles.includes(e.profileKey)&&e.normalized.unit==="g").reduce((s,e)=>s+num(e.normalized.value),0);
 const a2470=volume(["alcohol_24_70"]);if(a2470>0)checks.push({key:"alcohol_24_70_total",label:"Alcohol 24–70%",value:a2470,unit:"ml",limit:5000,status:a2470<=5000?"ok":"blocked",message:a2470<=5000?`Total ${(a2470/1000).toFixed(2)} L de 5 L FAA.`:`Total ${(a2470/1000).toFixed(2)} L: supera el máximo FAA de 5 L.`,sources:sourceRows(["FAA_ALCOHOL","TSA_ALCOHOL"])});
 const alcoholAll=volume(["alcohol_under24","alcohol_24_70"]);if(alcoholAll>0)checks.push({key:"alcohol_customs",label:"Alcohol / franquicia aduanera",value:alcoholAll,unit:"ml",reference:1000,status:alcoholAll<=1000?"ok":"declare",message:alcoholAll<=1000?`Total ${(alcoholAll/1000).toFixed(2)} L dentro de la referencia federal general de 1 L libre de aranceles para viajeros elegibles de 21+.`:`Total ${(alcoholAll/1000).toFixed(2)} L; ${(Math.max(0,alcoholAll-1000)/1000).toFixed(2)} L exceden la referencia general de 1 L y deben declararse, con posible arancel/impuesto.`,sources:sourceRows(["CBP_ALCOHOL","CBP_DUTY"])});
 const tv=volume(["toiletry_liquid","toiletry_aerosol"]),tm=mass(["toiletry_liquid","toiletry_aerosol"]);if(tv||tm)checks.push({key:"toiletry_total",label:"Artículos medicinales/de tocador",value:{ml:tv,g:tm},limit:{ml:2000,g:2000},status:tv<=2000&&tm<=2000?"ok":"review",message:tv<=2000&&tm<=2000?"Dentro de la referencia agregada FAA de 2 L / 2 kg para artículos cubiertos por esta excepción.":"El total supera 2 L / 2 kg; revisa cuáles artículos están cubiertos por la excepción FAA antes de viajar.",sources:sourceRows(["FAA_TOILETRIES"])});
 const cash=evals.filter(e=>e.profileKey==="cash"&&e.normalized.unit==="USD").reduce((s,e)=>s+num(e.normalized.value),0);if(cash>0)checks.push({key:"cash_total",label:"Efectivo e instrumentos monetarios",value:cash,unit:"USD",reference:10000,status:cash>10000?"declare":"ok",message:cash>10000?"Supera $10,000: FinCEN 105 y declaración obligatoria.":"No supera el umbral federal de reporte de más de $10,000.",sources:sourceRows(["CBP_CURRENCY"])});
 const batt=evals.filter(e=>e.normalized.unit==="Wh"&&num(e.normalized.value)>100&&num(e.normalized.value)<=160).reduce((s,e)=>s+Math.max(1,num(e.normalized.count,1)),0);if(batt)checks.push({key:"battery_101_160_count",label:"Baterías 101–160 Wh",value:batt,unit:"count",limit:2,status:batt<=2?"conditional":"blocked",message:batt<=2?"Requieren aprobación de aerolínea; máximo dos repuestos en este rango.":"Supera el máximo de dos baterías de repuesto de 101–160 Wh.",sources:sourceRows(["FAA_BATTERIES"])});
 return checks;}

async function probe(src:Obj){const c=new AbortController(),timer=setTimeout(()=>c.abort(),3500);try{const r=await fetch(src.url,{method:"GET",redirect:"follow",signal:c.signal,headers:{"User-Agent":"EntrySafe-USA/3.1 official-source-check"}});return {...src,reachable:r.ok,httpStatus:r.status,checkedAt:new Date().toISOString()};}catch{return {...src,reachable:false,httpStatus:0,checkedAt:new Date().toISOString()};}finally{clearTimeout(timer);}}

Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors});
 if(req.method!=="POST")return new Response(JSON.stringify({ok:false,error:"method_not_allowed"}),{status:405,headers:{...cors,"Content-Type":"application/json"}});
 try{
  const auth=req.headers.get("Authorization")||"";const sb=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_ANON_KEY")!,{global:{headers:{Authorization:auth}}});const user=await sb.auth.getUser();if(user.error||!user.data.user)throw new Error("Sesión inválida.");
  const body=await req.json();const tripId=String(body.tripId||"");const rawItems=Array.isArray(body.items)?body.items:[];if(!tripId||!rawItems.length)throw new Error("Selecciona un viaje y al menos un artículo.");if(rawItems.length>1000)throw new Error("La selección supera 1,000 artículos.");
  const [tripQ,profileQ]=await Promise.all([sb.from("trips").select("id,user_id,departure_date,entry_airport,entry_state,origin_country,destination_country").eq("id",tripId).eq("user_id",user.data.user.id).single(),sb.from("profiles").select("date_of_birth").eq("user_id",user.data.user.id).maybeSingle()]);if(tripQ.error||!tripQ.data)throw new Error("No se encontró el viaje o no te pertenece.");
  const travelerAge=ageAt(profileQ.data?.date_of_birth||null,tripQ.data.departure_date||new Date().toISOString().slice(0,10));
  const items:InputItem[]=rawItems.map((x:any)=>({catalogKey:String(x.catalogKey||"").slice(0,250),name:String(x.name||"Artículo").slice(0,180),profileKey:P[x.profileKey]?x.profileKey:"tsa_special",measurementKind:String(x.measurementKind||"count"),quantityValue:num(x.quantityValue,1),quantityUnit:String(x.quantityUnit||"unit"),presentations:Array.isArray(x.presentations)?x.presentations.slice(0,20).map((p:any)=>({count:num(p.count),size:num(p.size),unit:String(p.unit||"unit")})):[],abvPercent:num(x.abvPercent,0),batteryWh:num(x.batteryWh,0),batteryMah:num(x.batteryMah,0),batteryVoltage:num(x.batteryVoltage,0),daysSupply:num(x.daysSupply,0)}));
  if(items.some(i=>!i.catalogKey))throw new Error("La selección contiene una clave de catálogo inválida.");
  const evals=items.map(i=>evaluate(i,travelerAge));const aggregateChecks=aggregate(evals);
  for(const check of aggregateChecks.filter((x:any)=>x.status==="blocked")){if(check.key==="alcohol_24_70_total")for(const e of evals.filter(e=>e.profileKey==="alcohol_24_70")){e.decision="prohibited";e.recommendedBag="none";e.requirements.push("El total combinado de alcohol 24–70% supera 5 L FAA.");}if(check.key==="battery_101_160_count")for(const e of evals.filter(e=>e.normalized.unit==="Wh"&&num(e.normalized.value)>100&&num(e.normalized.value)<=160)){e.decision="prohibited";e.recommendedBag="none";e.requirements.push("El total de baterías de repuesto 101–160 Wh supera dos.");}}
  const sourceKeys=unique(evals.flatMap(e=>e.sources.map((s:any)=>s.key)));const probed=await Promise.all(sourceKeys.map(k=>probe({key:k,...SOURCES[k]})));const probeMap=Object.fromEntries(probed.map(x=>[x.key,x]));for(const e of evals)e.sources=e.sources.map((s:any)=>probeMap[s.key]||{...s,reachable:null,checkedAt:new Date().toISOString()});
  const counts={allowed:0,allowed_declare:0,conditional:0,prohibited:0,review:0};for(const e of evals)(counts as any)[e.decision]=((counts as any)[e.decision]||0)+1;const summary={total:evals.length,...counts,ready:counts.allowed,declare:counts.allowed_declare,attention:counts.conditional+counts.review,blocked:counts.prohibited,engineVersion:VERSION,catalogVersion:body.catalogVersion||null,entryState:tripQ.data.entry_state||body.entryState||null,travelerAge};
  const batch=await sb.from("trip_selection_batches_v3").insert({trip_id:tripId,user_id:user.data.user.id,item_count:evals.length,summary,aggregate_checks:aggregateChecks,source_snapshot:probed}).select("id,created_at").single();if(batch.error)throw batch.error;
  const rows=evals.map(e=>{const input=e.input;return {trip_id:tripId,user_id:user.data.user.id,catalog_key_v3:e.catalogKey,profile_key_v3:e.profileKey,custom_name:e.name,quantity:num(input.quantityValue,1),unit:String(input.quantityUnit||"unit"),quantity_value:num(input.quantityValue,1),quantity_unit:String(input.quantityUnit||"unit"),presentations_v3:input.presentations||[],abv_percent:num(input.abvPercent,0)||null,battery_wh:e.normalized.unit==="Wh"?e.normalized.value:(num(input.batteryWh,0)||null),battery_mah:num(input.batteryMah,0)||null,battery_voltage:num(input.batteryVoltage,0)||null,days_supply:num(input.daysSupply,0)||null,computed_decision:e.decision==="conditional"?"restricted":e.decision,computed_risk:e.decision==="prohibited"?"high":e.decision==="review"?"review":e.decision==="conditional"?"medium":"low",regulatory_required:e.profileKey!=="ordinary",evaluation_v3:{engineVersion:VERSION,decision:e.decision,declarationRequired:e.declarationRequired,recommendedBag:e.recommendedBag,requirements:e.requirements,normalized:e.normalized,travelerAge,aggregateChecks:aggregateChecks.filter((c:any)=>(String(c.key).includes("alcohol")&&e.profileKey.startsWith("alcohol"))||(c.key==="toiletry_total"&&e.profileKey.startsWith("toiletry"))||(c.key==="cash_total"&&e.profileKey==="cash")||(c.key==="battery_101_160_count"&&e.normalized.unit==="Wh"))},source_snapshot_v3:e.sources,recommended_bag_v3:e.recommendedBag,selection_batch_id:batch.data.id,rule_version:VERSION};});
  const existing=await sb.from("trip_items").select("id,catalog_key_v3").eq("trip_id",tripId).eq("user_id",user.data.user.id).not("catalog_key_v3","is",null);if(existing.error)throw existing.error;
  const up=await sb.from("trip_items").upsert(rows,{onConflict:"user_id,trip_id,catalog_key_v3"});if(up.error)throw up.error;
  const keep=new Set(rows.map(r=>r.catalog_key_v3));const stale=(existing.data||[]).filter((r:any)=>!keep.has(r.catalog_key_v3)).map((r:any)=>r.id);if(stale.length){const del=await sb.from("trip_items").delete().in("id",stale);if(del.error)throw del.error;}
  return new Response(JSON.stringify({ok:true,batchId:batch.data.id,createdAt:batch.data.created_at,summary,aggregateChecks,items:evals.map(({input,...e})=>e),finalNotice:"Las decisiones de EntrySafe son una guía de preparación basada en fuentes oficiales. La determinación final de admisibilidad corresponde a CBP/USDA y la decisión final de seguridad del equipaje corresponde a TSA/FAA y la aerolínea."}),{headers:{...cors,"Content-Type":"application/json","Cache-Control":"no-store"}});
 }catch(error){return new Response(JSON.stringify({ok:false,error:error instanceof Error?error.message:String(error),engineVersion:VERSION}),{status:400,headers:{...cors,"Content-Type":"application/json","Cache-Control":"no-store"}});}
});
