import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
import {VERSION,SOURCES,PROFILES,evaluate,aggregate,num,type InputItem} from "./rules.ts";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type, x-client-info","Access-Control-Allow-Methods":"POST, OPTIONS"};
async function probeSource(src:any){const c=new AbortController();const t=setTimeout(()=>c.abort(),3200);try{const r=await fetch(src.url,{method:"GET",redirect:"follow",signal:c.signal,headers:{"User-Agent":"EntrySafe-USA/3.1 official-source-check"}});return {...src,reachable:r.ok,httpStatus:r.status,checkedAt:new Date().toISOString()};}catch{return {...src,reachable:false,httpStatus:0,checkedAt:new Date().toISOString()};}finally{clearTimeout(t);}}
function applyAggregateBlocks(evals:any[],checks:any[]){for(const c of checks.filter(x=>x.status==="blocked")){if(c.key==="alcohol_24_70_total")evals.filter(e=>e.profileKey==="alcohol_24_70").forEach(e=>{e.decision="prohibited";e.requirements.push("El total combinado de alcohol 24–70% supera 5 L FAA.");});if(c.key==="toiletry_total")evals.filter(e=>["toiletry_liquid","toiletry_aerosol"].includes(e.profileKey)).forEach(e=>{e.decision="prohibited";e.requirements.push("El total combinado supera 2 L / 2 kg FAA.");});if(c.key==="battery_101_160_count")evals.filter(e=>e.profileKey==="power_bank_160").forEach(e=>{e.decision="prohibited";e.requirements.push("El total de baterías de repuesto 101–160 Wh supera dos.");});}}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return new Response(JSON.stringify({ok:false,error:"method_not_allowed"}),{status:405,headers:{...cors,"Content-Type":"application/json"}});try{
 const auth=req.headers.get("Authorization")||"";const sb=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_ANON_KEY")!,{global:{headers:{Authorization:auth}}});const user=await sb.auth.getUser();if(user.error||!user.data.user)throw new Error("Sesión inválida.");
 const body=await req.json();const tripId=String(body.tripId||"");const raw=Array.isArray(body.items)?body.items:[];if(!tripId||!raw.length)throw new Error("Selecciona un viaje y al menos un artículo.");if(raw.length>1000)throw new Error("La selección supera 1,000 artículos.");
 const trip=await sb.from("trips").select("id,user_id,entry_airport,entry_state,origin_country,destination_country").eq("id",tripId).eq("user_id",user.data.user.id).single();if(trip.error||!trip.data)throw new Error("No se encontró el viaje o no te pertenece.");
 const items:InputItem[]=raw.map((x:any)=>({catalogKey:String(x.catalogKey||""),name:String(x.name||"Artículo"),profileKey:PROFILES[x.profileKey]?x.profileKey:"tsa_special",measurementKind:String(x.measurementKind||"count"),quantityValue:num(x.quantityValue,1),quantityUnit:String(x.quantityUnit||"unit"),presentations:Array.isArray(x.presentations)?x.presentations.slice(0,20):[],abvPercent:num(x.abvPercent,0),batteryWh:num(x.batteryWh,0),batteryMah:num(x.batteryMah,0),batteryVoltage:num(x.batteryVoltage,0),daysSupply:num(x.daysSupply,0),bagPreference:String(x.bagPreference||"")}));
 const evals=items.map(evaluate);const aggregateChecks=aggregate(evals);applyAggregateBlocks(evals,aggregateChecks);
 const sourceKeys=[...new Set(evals.flatMap(e=>e.sources.map((s:any)=>s.key)))];const probes=await Promise.all(sourceKeys.slice(0,16).map(k=>probeSource({key:k,...SOURCES[k]})));const probeMap=Object.fromEntries(probes.map(x=>[x.key,x]));for(const e of evals)e.sources=e.sources.map((s:any)=>probeMap[s.key]||{...s,checkedAt:new Date().toISOString(),reachable:null});
 const counts:any={allowed:0,allowed_declare:0,conditional:0,prohibited:0,review:0};for(const e of evals)counts[e.decision]=(counts[e.decision]||0)+1;const summary={total:evals.length,...counts,ready:counts.allowed,declare:counts.allowed_declare,attention:counts.conditional+counts.review,blocked:counts.prohibited,engineVersion:VERSION,catalogVersion:body.catalogVersion||null,entryState:trip.data.entry_state||body.entryState||null};
 const batch=await sb.from("trip_selection_batches_v3").insert({trip_id:tripId,user_id:user.data.user.id,item_count:evals.length,summary,aggregate_checks:aggregateChecks,source_snapshot:probes}).select("id,created_at").single();if(batch.error)throw batch.error;
 const payloads=evals.map((e:any)=>{const input=e.input;return {trip_id:tripId,user_id:user.data.user.id,catalog_key_v3:e.catalogKey,profile_key_v3:e.profileKey,custom_name:e.name,quantity:num(input.quantityValue,1),unit:String(input.quantityUnit||"unit"),quantity_value:num(input.quantityValue,1),quantity_unit:String(input.quantityUnit||"unit"),presentations_v3:input.presentations||[],abv_percent:num(input.abvPercent,0)||null,battery_wh:e.normalized.unit==="Wh"?e.normalized.value:(num(input.batteryWh,0)||null),battery_mah:num(input.batteryMah,0)||null,battery_voltage:num(input.batteryVoltage,0)||null,days_supply:num(input.daysSupply,0)||null,computed_decision:e.decision==="conditional"?"restricted":e.decision,computed_risk:e.decision==="prohibited"?"high":e.decision==="review"?"review":e.decision==="conditional"?"medium":"low",regulatory_required:e.profileKey!=="ordinary",evaluation_v3:{engineVersion:VERSION,decision:e.decision,declarationRequired:e.declarationRequired,recommendedBag:e.recommendedBag,requirements:e.requirements,normalized:e.normalized},source_snapshot_v3:e.sources,recommended_bag_v3:e.recommendedBag,selection_batch_id:batch.data.id,rule_version:VERSION};});
 const up=await sb.from("trip_items").upsert(payloads,{onConflict:"user_id,trip_id,catalog_key_v3"});if(up.error)throw up.error;
 return new Response(JSON.stringify({ok:true,batchId:batch.data.id,createdAt:batch.data.created_at,summary,aggregateChecks,items:evals.map(({input,...e}:any)=>e),finalNotice:"EntrySafe prepara el viaje con fuentes oficiales. La determinación final de admisibilidad corresponde a CBP/USDA y la decisión final de seguridad corresponde a TSA/FAA/aerolínea."}),{headers:{...cors,"Content-Type":"application/json","Cache-Control":"no-store"}});
 }catch(error){return new Response(JSON.stringify({ok:false,error:error instanceof Error?error.message:String(error),engineVersion:VERSION}),{status:400,headers:{...cors,"Content-Type":"application/json","Cache-Control":"no-store"}});}});
