export type AnyObj=Record<string,any>;
export type InputItem={catalogKey:string;name:string;profileKey:string;measurementKind?:string;quantityValue?:number;quantityUnit?:string;presentations?:Array<{count:number;size:number;unit:string}>;abvPercent?:number;batteryWh?:number;batteryMah?:number;batteryVoltage?:number;daysSupply?:number;bagPreference?:string};
export const VERSION="3.1.0-20260830";
export const SOURCES:Record<string,AnyObj>={
 APHIS_GENERAL:{agency:"USDA-APHIS",title:"Traveling From Another Country",url:"https://www.aphis.usda.gov/traveling-with-ag-products/another-country",verified:"2026-03-31"},
 APHIS_MEAT:{agency:"USDA-APHIS",title:"Meats, Poultry, and Seafood",url:"https://www.aphis.usda.gov/traveling-with-ag-products/meats-poultry-seafood",verified:"2026-01-13"},
 APHIS_DAIRY:{agency:"USDA-APHIS",title:"Milk, Dairy, and Egg Products",url:"https://www.aphis.usda.gov/traveling-with-ag-products/milk-dairy-eggs",verified:"2026-01-13"},
 APHIS_PRODUCE:{agency:"USDA-APHIS",title:"Fruits and Vegetables",url:"https://www.aphis.usda.gov/traveling-with-ag-products/fruits-vegetables",verified:"2026-01-13"},
 APHIS_PANTRY:{agency:"USDA-APHIS",title:"Coffee, Teas, Honey, Nuts, and Spices",url:"https://www.aphis.usda.gov/traveling-with-ag-products/coffee-tea-honey-nuts-spices",verified:"2026-01-13"},
 APHIS_PLANTS:{agency:"USDA-APHIS",title:"Plants, Plant Parts, Cut Flowers, and Seeds",url:"https://www.aphis.usda.gov/traveling-with-ag-products/plants-plant-parts",verified:"2026-02-24"},
 APHIS_SOIL:{agency:"USDA-APHIS",title:"Soil and Soil-Related Products",url:"https://www.aphis.usda.gov/traveling-with-ag-products/soil",verified:"2026-01-13"},
 APHIS_SOUVENIRS:{agency:"USDA-APHIS",title:"Souvenirs",url:"https://www.aphis.usda.gov/traveling-with-ag-products/souvenirs",verified:"2026-01-13"},
 APHIS_HEALTH:{agency:"USDA-APHIS",title:"Region Health Status - Animals",url:"https://www.aphis.usda.gov/regionalization-evaluation-services/region-health-status",verified:"2026-08-30"},
 ACIR:{agency:"USDA-APHIS",title:"Agricultural Commodity Import Requirements",url:"https://acir.aphis.usda.gov/",verified:"2026-08-30"},
 CBP_DECLARE:{agency:"CBP",title:"Qué artículos debo declarar",url:"https://www.help.cbp.gov/s/article/Article-1909?language=es",verified:"2026-02-13"},
 CBP_ALCOHOL:{agency:"CBP",title:"Alcohol para uso personal",url:"https://www.help.cbp.gov/s/article/Article-1395?language=es",verified:"2026-02-13"},
 CBP_DUTY:{agency:"CBP",title:"Customs Duty Information",url:"https://www.cbp.gov/travel/international-visitors/know-before-you-visit/customs-duty-information",verified:"2026-08-30"},
 CBP_CURRENCY:{agency:"CBP",title:"Currency and Monetary Instruments",url:"https://www.help.cbp.gov/s/article/Article-1393?language=en_US",verified:"2026-03-29"},
 CBP_TOBACCO:{agency:"CBP",title:"Tobacco Products for Personal Use",url:"https://www.help.cbp.gov/s/article/Article-1376?language=en_US",verified:"2026-04-22"},
 TSA_ALL:{agency:"TSA",title:"What Can I Bring?",url:"https://www.tsa.gov/travel/security-screening/whatcanibring/all-list",verified:"2026-08-30"},
 TSA_ALCOHOL:{agency:"TSA",title:"Alcoholic Beverages",url:"https://www.tsa.gov/travel/security-screening/whatcanibring/items/alcoholic-beverages",verified:"2026-08-30"},
 TSA_TIPS:{agency:"TSA",title:"TSA Travel Tips / 3-1-1",url:"https://www.tsa.gov/news/press/factsheets/tsa-travel-tips",verified:"2026-08-30"},
 FAA_PACKSAFE:{agency:"FAA",title:"PackSafe for Passengers",url:"https://www.faa.gov/hazmat/packsafe",verified:"2026-08-30"},
 FAA_ALCOHOL:{agency:"FAA",title:"PackSafe - Alcoholic Beverages",url:"https://www.faa.gov/hazmat/packsafe/alcoholic-beverages",verified:"2026-04-13"},
 FAA_BATTERIES:{agency:"FAA",title:"PackSafe - Batteries",url:"https://www.faa.gov/hazmat/packsafe/batteries",verified:"2025-01-22"},
 FAA_TOILETRIES:{agency:"FAA",title:"PackSafe - Medicinal & Toiletry Articles",url:"https://www.faa.gov/hazmat/packsafe/medicinal-toiletry-articles",verified:"2024-06-07"},
 FAA_DRY_ICE:{agency:"FAA",title:"PackSafe - Dry Ice",url:"https://www.faa.gov/hazmat/packsafe/dry-ice",verified:"2024-01-25"},
 FAA_LIGHTERS:{agency:"FAA",title:"PackSafe - Lighters",url:"https://www.faa.gov/hazmat/packsafe/lighters",verified:"2026-04-13"},
 FAA_VAPE:{agency:"FAA",title:"PackSafe - Electronic Cigarettes, Vaping Devices",url:"https://www.faa.gov/hazmat/packsafe/e-cigarettes-vaping",verified:"2026-04-13"},
 FAA_OXYGEN:{agency:"FAA",title:"PackSafe - Oxygen",url:"https://www.faa.gov/hazmat/packsafe/oxygen-compressed-or-liquid",verified:"2026-04-13"},
 FDA_PERSONAL:{agency:"FDA",title:"Personal Importation",url:"https://www.fda.gov/importeddrugs",verified:"2026-08-30"},
 FDA_MEDS:{agency:"FDA",title:"Traveling with Prescription Medications",url:"https://www.fda.gov/drugs/fda-drug-info-rounds-video/traveling-prescription-medications",verified:"2026-08-30"},
 FWS_IMPORT:{agency:"USFWS",title:"Information for Importers & Exporters",url:"https://www.fws.gov/program/office-of-law-enforcement/information-importers-exporters",verified:"2026-08-30"}
};
export const PROFILES:Record<string,AnyObj>={
 ordinary:{d:"allowed",declare:false,bag:"either",src:["TSA_ALL"],req:["Sujeto a la decisión final de TSA y a la política de la aerolínea."]},
 tsa_liquid:{d:"allowed",declare:false,bag:"checked_if_over_100ml",src:["TSA_TIPS","TSA_ALL"],req:["En carry-on, cada envase normalmente debe ser de 100 ml (3.4 fl oz) o menos."]},
 tsa_medical_liquid:{d:"allowed",declare:false,bag:"carry_on",src:["TSA_TIPS"],req:["Los líquidos médicamente necesarios pueden superar 100 ml; decláralos para inspección separada."]},
 toiletry_liquid:{d:"allowed",declare:false,bag:"checked_if_over_100ml",src:["FAA_TOILETRIES","TSA_TIPS"],req:["Máximo agregado: 2 L o 2 kg por persona.","Máximo por envase: 500 ml o 0.5 kg.","En carry-on, cada envase normalmente debe ser de 100 ml o menos."]},
 toiletry_aerosol:{d:"allowed",declare:false,bag:"checked_if_over_100ml",src:["FAA_TOILETRIES","TSA_TIPS"],req:["Cuenta dentro del máximo agregado de 2 L o 2 kg.","Máximo por envase: 500 ml o 0.5 kg.","Protege la boquilla contra liberación accidental."]},
 alcohol_under24:{d:"allowed_declare",declare:true,bag:"checked_if_over_100ml",src:["CBP_ALCOHOL","CBP_DUTY","TSA_ALCOHOL","FAA_ALCOHOL"],req:["Edad mínima: 21 años.","Franquicia federal general: 1 L; el excedente debe declararse y puede pagar arancel/impuesto.","En carry-on, cada envase debe ser de 100 ml o menos.","Verifica además la ley del estado de entrada."]},
 alcohol_24_70:{d:"allowed_declare",declare:true,bag:"checked_if_over_100ml",src:["CBP_ALCOHOL","CBP_DUTY","TSA_ALCOHOL","FAA_ALCOHOL"],req:["Edad mínima: 21 años.","Máximo FAA: 5 L totales por pasajero.","Debe estar en empaque comercial sin abrir.","En carry-on, cada envase debe ser de 100 ml o menos.","Franquicia federal general: 1 L; el excedente debe declararse y puede pagar arancel/impuesto.","Verifica además la ley del estado de entrada."]},
 alcohol_over70:{d:"prohibited",declare:true,bag:"none",src:["TSA_ALCOHOL","FAA_ALCOHOL"],req:["Más de 70% ABV no está permitido en equipaje de pasajeros."]},
 coffee_roasted:{d:"allowed_declare",declare:true,bag:"either",src:["APHIS_PANTRY","CBP_DECLARE"],req:["USDA permite cantidades ilimitadas de café tostado en equipaje.","Debe declararse al entrar."]},
 coffee_green:{d:"allowed_declare",declare:true,bag:"either",src:["APHIS_PANTRY","CBP_DECLARE"],req:["Permitido en cantidades ilimitadas hacia Estados Unidos continental.","No aplica igual para Hawaii o Puerto Rico.","Debe declararse."]},
 coffee_cherry:{d:"prohibited",declare:true,bag:"none",src:["APHIS_PANTRY"],req:["La cereza fresca de café está prohibida en todos los puertos de entrada."]},
 fruit_fresh:{d:"prohibited",declare:true,bag:"none",src:["APHIS_PRODUCE","ACIR"],req:["APHIS indica que casi todas las frutas frescas están prohibidas; una excepción específica debe resolverse en ACIR."]},
 vegetable_fresh:{d:"prohibited",declare:true,bag:"none",src:["APHIS_PRODUCE","ACIR"],req:["APHIS indica que casi todos los vegetales frescos están prohibidos; una excepción específica debe resolverse en ACIR."]},
 produce_frozen:{d:"prohibited",declare:true,bag:"none",src:["APHIS_PRODUCE"],req:["APHIS indica que casi todas las frutas y vegetales congelados están prohibidos."]},
 produce_canned_commercial:{d:"allowed_declare",declare:true,bag:"either",src:["APHIS_PRODUCE","CBP_DECLARE"],req:["Las frutas y vegetales comercialmente enlatados pueden ingresar si se declaran."]},
 produce_home_canned:{d:"prohibited",declare:true,bag:"none",src:["APHIS_PRODUCE"],req:["APHIS no permite conservas caseras de frutas o vegetales."]},
 produce_dried:{d:"review",declare:true,bag:"conditional",src:["APHIS_PRODUCE","ACIR"],req:["La mayoría de productos secos requieren revisión específica; algunos están expresamente permitidos."]},
 spices_dried:{d:"allowed_declare",declare:true,bag:"either",src:["APHIS_PANTRY","CBP_DECLARE"],req:["La mayoría de especias secas pueden importarse, con excepciones específicas.","Debe declararse."]},
 nuts_roasted:{d:"allowed_declare",declare:true,bag:"either",src:["APHIS_PANTRY","CBP_DECLARE"],req:["Las nueces cocidas o tostadas están permitidas.","Debe declararse."]},
 honey:{d:"allowed_declare",declare:true,bag:"either",src:["APHIS_PANTRY","CBP_DECLARE"],req:["Generalmente permitido para consumo personal.","Debe declararse."]},
 seed_food:{d:"review",declare:true,bag:"conditional",src:["APHIS_PANTRY","ACIR"],req:["Semillas y granos pueden tener restricciones fitosanitarias; requiere resolución específica si no hay regla directa."]},
 dry_food:{d:"allowed_declare",declare:true,bag:"either",src:["APHIS_GENERAL","CBP_DECLARE"],req:["Declara los alimentos/productos agrícolas; la decisión final corresponde a CBP/USDA."]},
 baked_goods:{d:"allowed_declare",declare:true,bag:"either",src:["APHIS_GENERAL","APHIS_DAIRY","CBP_DECLARE"],req:["Declara el alimento; si contiene ingredientes restringidos puede aplicar una regla más estricta."]},
 prepared_mixed:{d:"review",declare:true,bag:"conditional",src:["APHIS_GENERAL","APHIS_MEAT","APHIS_DAIRY","APHIS_PRODUCE","CBP_DECLARE"],req:["La decisión depende de los ingredientes; una comida mixta no se autoriza automáticamente sin evidencia suficiente."]},
 poultry_cooked:{d:"allowed_declare",declare:true,bag:"either",src:["APHIS_MEAT","APHIS_HEALTH","CBP_DECLARE"],req:["Debe estar completamente cocido en toda su extensión.","Debe declararse y puede ser inspeccionado.","Máximo de equipaje personal: 50 lb por artículo."]},
 poultry_raw:{d:"review",declare:true,bag:"conditional",src:["APHIS_MEAT","APHIS_HEALTH"],req:["La admisibilidad depende del estado sanitario vigente del país de origen para HPAI/Newcastle."]},
 poultry_shelf_stable:{d:"allowed_declare",declare:true,bag:"either",src:["APHIS_MEAT","CBP_DECLARE"],req:["Debe ser comercial, etiquetado, cocido, shelf-stable y estar sin abrir.","Máximo 50 lb por artículo."]},
 pork_general:{d:"review",declare:true,bag:"conditional",src:["APHIS_MEAT","APHIS_HEALTH"],req:["La admisibilidad depende del estado sanitario vigente del país de origen.","Debe declararse."]},
 pork_processed:{d:"review",declare:true,bag:"conditional",src:["APHIS_MEAT","APHIS_HEALTH"],req:["Productos de cerdo están sujetos a restricciones de sanidad animal según origen y preparación."]},
 ruminant_meat:{d:"review",declare:true,bag:"conditional",src:["APHIS_MEAT","APHIS_HEALTH"],req:["La admisibilidad depende del estado sanitario del país de origen."]},
 dairy:{d:"review",declare:true,bag:"either",src:["APHIS_DAIRY","APHIS_HEALTH","CBP_DECLARE"],req:["Mantequilla y quesos sólidos sin carne que no sean líquidos pueden ingresar desde cualquier país.","Otros lácteos dependen del estatus de FMD y de su procesamiento."]},
 dairy_processed:{d:"allowed_declare",declare:true,bag:"either",src:["APHIS_DAIRY","CBP_DECLARE"],req:["Productos con leche seca correctamente etiquetados y ciertos alimentos comerciales shelf-stable sin abrir tienen excepciones."]},
 egg_product:{d:"review",declare:true,bag:"conditional",src:["APHIS_DAIRY","APHIS_HEALTH","CBP_DECLARE"],req:["La admisibilidad depende de HPAI/Newcastle; productos completamente cocidos pueden ser admitidos tras inspección."]},
 seafood:{d:"review",declare:true,bag:"either",src:["APHIS_MEAT","FDA_PERSONAL","FWS_IMPORT","CBP_DECLARE"],req:["APHIS no regula la mayoría de mariscos; FDA/USFWS pueden aplicar según especie o producto."]},
 seafood_breaded:{d:"review",declare:true,bag:"either",src:["APHIS_MEAT","FDA_PERSONAL"],req:["El empanizado puede activar reglas de ingredientes de origen animal."]},
 plant_material:{d:"review",declare:true,bag:"conditional",src:["APHIS_PLANTS","ACIR","CBP_DECLARE"],req:["Puede requerir permiso, certificado o inspección; consulta ACIR por mercancía específica."]},
 plant_seed:{d:"review",declare:true,bag:"conditional",src:["APHIS_PLANTS","ACIR","CBP_DECLARE"],req:["Semillas para propagación pueden requerir certificado fitosanitario, permiso o estar prohibidas."]},
 soil:{d:"prohibited",declare:true,bag:"none",src:["APHIS_SOIL","CBP_DECLARE"],req:["El suelo extranjero está fuertemente restringido y generalmente requiere permiso/tratamiento."]},
 plant_souvenir:{d:"review",declare:true,bag:"conditional",src:["APHIS_SOUVENIRS","ACIR","CBP_DECLARE"],req:["Materiales vegetales pueden requerir inspección o restricciones."]},
 wildlife_souvenir:{d:"review",declare:true,bag:"conditional",src:["FWS_IMPORT","APHIS_SOUVENIRS","CBP_DECLARE"],req:["Productos de fauna pueden estar sujetos a USFWS/CITES y requieren revisión por especie/material."]},
 lithium_device:{d:"allowed",declare:false,bag:"carry_on_preferred",src:["FAA_BATTERIES","TSA_ALL"],req:["Si se factura, el dispositivo debe estar completamente apagado y protegido.","Baterías de repuesto deben ir en carry-on."]},
 power_bank_100:{d:"allowed",declare:false,bag:"carry_on",src:["FAA_BATTERIES","TSA_ALL"],req:["Debe ir en carry-on o en la persona; no en equipaje facturado.","Proteger terminales contra cortocircuito."]},
 power_bank_160:{d:"conditional",declare:false,bag:"carry_on",src:["FAA_BATTERIES","TSA_ALL"],req:["Requiere aprobación de la aerolínea.","Máximo dos baterías de repuesto de 101–160 Wh.","Debe ir en carry-on."]},
 battery_over160:{d:"prohibited",declare:false,bag:"none",src:["FAA_BATTERIES"],req:["Más de 160 Wh no se permite como batería estándar de pasajero."]},
 dry_battery:{d:"allowed",declare:false,bag:"either",src:["FAA_BATTERIES"],req:["Proteger contra daño y cortocircuito."]},
 medication:{d:"allowed_declare",declare:true,bag:"carry_on_preferred",src:["FDA_PERSONAL","FDA_MEDS","CBP_DECLARE"],req:["Para visitantes extranjeros, FDA permite generalmente hasta 90 días de suministro personal.","Mantener en envase original y llevar receta/carta médica cuando corresponda."]},
 controlled_medication_review:{d:"review",declare:true,bag:"carry_on_preferred",src:["FDA_PERSONAL","FDA_MEDS","CBP_DECLARE"],req:["Las sustancias controladas tienen reglas adicionales; requiere revisión específica del medicamento."]},
 medical_device:{d:"allowed",declare:false,bag:"either",src:["TSA_ALL","FDA_PERSONAL"],req:["Puede requerir inspección; verifica aerolínea para equipos grandes o con baterías."]},
 animal_product_review:{d:"review",declare:true,bag:"conditional",src:["APHIS_MEAT","APHIS_HEALTH"],req:["Ingredientes de origen animal pueden activar requisitos sanitarios específicos."]},
 cash:{d:"allowed",declare:false,bag:"either",src:["CBP_CURRENCY"],req:["Es legal transportar cualquier cantidad.","Si el total combinado supera $10,000 USD o equivalente, debes declarar y presentar FinCEN 105."]},
 tobacco_cigarette:{d:"conditional",declare:true,bag:"either",src:["CBP_TOBACCO","CBP_DECLARE"],req:["La exención personal de viajeros elegibles contempla hasta 200 cigarrillos.","Edad mínima 21."]},
 tobacco_cigar:{d:"conditional",declare:true,bag:"either",src:["CBP_TOBACCO","CBP_DECLARE"],req:["La exención personal de viajeros elegibles contempla hasta 100 puros.","Edad mínima 21."]},
 tobacco_other:{d:"review",declare:true,bag:"conditional",src:["CBP_TOBACCO","CBP_DECLARE"],req:["Límites y exenciones dependen del tipo de tabaco y estatus del viajero."]},
 checked_only_tool:{d:"conditional",declare:false,bag:"checked",src:["TSA_ALL"],req:["No debe ir en carry-on; empácalo en equipaje facturado y verifica la aerolínea."]},
 tsa_special:{d:"review",declare:false,bag:"conditional",src:["TSA_ALL","FAA_PACKSAFE"],req:["Tiene instrucciones específicas TSA/FAA; requiere revisión del artículo concreto."]},
 dry_ice:{d:"conditional",declare:false,bag:"conditional",src:["FAA_DRY_ICE","TSA_ALL"],req:["Máximo 2.5 kg (5.5 lb) por pasajero y paquete.","Requiere aprobación de la aerolínea.","El empaque debe permitir ventilación de CO2."]},
 vape:{d:"conditional",declare:false,bag:"carry_on",src:["FAA_VAPE","TSA_ALL"],req:["Debe ir en la persona o carry-on, nunca facturado.","Evitar activación accidental y no recargar a bordo.","Cada batería ≤100 Wh."]},
 lighter:{d:"conditional",declare:false,bag:"carry_on",src:["FAA_LIGHTERS","TSA_ALL"],req:["Máximo un encendedor común por pasajero en carry-on o en la persona; soplete prohibido."]},
 oxygen:{d:"prohibited",declare:false,bag:"none",src:["FAA_OXYGEN"],req:["El pasajero no puede llevar su propio oxígeno comprimido o líquido; coordina con la aerolínea."]}
};
const MASS:Record<string,number>={mg:.001,g:1,kg:1000,oz:28.349523125,lb:453.59237};
const VOL:Record<string,number>={ml:1,L:1000,fl_oz:29.5735295625,cup:236.588,pint:473.176,quart:946.353,gallon:3785.411784};
export const num=(v:any,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function totalBase(item:InputItem){const pres=Array.isArray(item.presentations)?item.presentations.filter(x=>num(x.count)>0&&num(x.size)>0):[];if(pres.length){if(item.measurementKind==="mass")return pres.reduce((s,x)=>s+num(x.count)*num(x.size)*(MASS[x.unit]||0),0);if(item.measurementKind==="volume")return pres.reduce((s,x)=>s+num(x.count)*num(x.size)*(VOL[x.unit]||0),0);}if(item.measurementKind==="mass")return num(item.quantityValue,1)*(MASS[item.quantityUnit||"lb"]||1);if(item.measurementKind==="volume")return num(item.quantityValue,1)*(VOL[item.quantityUnit||"ml"]||1);if(item.measurementKind==="days")return num(item.daysSupply||item.quantityValue,1);if(item.measurementKind==="money")return num(item.quantityValue,0);return num(item.quantityValue,1);}
const maxPresentationMl=(item:InputItem)=>Math.max(0,...(item.presentations||[]).map(x=>num(x.size)*(VOL[x.unit]||0)),item.measurementKind==="volume"?num(item.quantityValue)*(VOL[item.quantityUnit||"ml"]||1):0);
export const sourceRows=(keys:string[])=>[...new Set(keys)].map(k=>({key:k,...SOURCES[k]})).filter(x=>x.url);
export function evaluate(item:InputItem){const p=PROFILES[item.profileKey]||PROFILES.tsa_special;let decision=p.d,declare=!!p.declare,bag=p.bag;const req=[...p.req];const base=totalBase(item);let normalized:any={kind:item.measurementKind||"count",value:base,unit:item.measurementKind==="mass"?"g":item.measurementKind==="volume"?"ml":item.measurementKind==="days"?"days":item.measurementKind==="money"?"USD":"count"};const name=(item.name||"").toLowerCase();
 if(["poultry_cooked","poultry_shelf_stable"].includes(item.profileKey)&&base>22679.6185){decision="review";req.push("Supera 50 lb por artículo; APHIS lo trata como envío comercial.");}
 if(item.profileKey==="dairy"&&["mantequilla","queso sólido","quesillo","queso fresco","queso seco","queso crema","mozzarella","cheddar","parmesano","queso rallado"].some(x=>name.includes(x))){decision="allowed_declare";req.push("APHIS permite mantequilla y quesos sólidos duros o blandos desde cualquier país si no contienen carne y no son líquidos.");}
 if(item.profileKey==="medication"&&num(item.daysSupply||item.quantityValue,0)>90){decision="review";req.push("Supera la referencia FDA de 90 días; requiere revisión/documentación adicional.");}
 if(["power_bank_100","power_bank_160","battery_over160","vape"].includes(item.profileKey)){let wh=num(item.batteryWh,0);if(!wh&&num(item.batteryMah)>0&&num(item.batteryVoltage)>0)wh=num(item.batteryMah)*num(item.batteryVoltage)/1000;normalized={kind:"battery",value:wh,unit:"Wh"};if(wh>160){decision="prohibited";bag="none";req.push("La capacidad calculada supera 160 Wh.");}else if(wh>100){decision="conditional";bag="carry_on";req.push("Capacidad 101–160 Wh: aprobación de aerolínea y máximo dos repuestos.");}else if(wh>0){decision="allowed";bag="carry_on";}}
 if(["tsa_liquid","toiletry_liquid","toiletry_aerosol","alcohol_under24","alcohol_24_70"].includes(item.profileKey)&&maxPresentationMl(item)>100)bag="checked";
 if(["toiletry_liquid","toiletry_aerosol"].includes(item.profileKey)&&maxPresentationMl(item)>500){decision="prohibited";req.push("Algún envase supera 500 ml, máximo FAA por envase para esta excepción.");}
 if(item.profileKey==="dry_ice"&&base>2500){decision="prohibited";req.push("Supera 2.5 kg (5.5 lb), máximo FAA.");}
 if(item.profileKey==="lighter"&&base>1){decision="prohibited";req.push("Supera el límite de un encendedor común por pasajero.");}
 if(item.profileKey==="cash"&&base>10000){declare=true;decision="allowed_declare";req.push("Total superior a $10,000: debes declarar y presentar FinCEN 105.");}
 return {catalogKey:item.catalogKey,name:item.name,profileKey:item.profileKey,decision,declarationRequired:declare,recommendedBag:bag,requirements:[...new Set(req)],normalized,sources:sourceRows(p.src),presentations:item.presentations||[],input:item};}
export function aggregate(evals:any[]){const checks:any[]=[];const vol=(keys:string[])=>evals.filter(e=>keys.includes(e.profileKey)).reduce((s,e)=>s+(e.normalized.unit==="ml"?e.normalized.value:0),0);const mass=(keys:string[])=>evals.filter(e=>keys.includes(e.profileKey)).reduce((s,e)=>s+(e.normalized.unit==="g"?e.normalized.value:0),0);
 const alcohol2470=vol(["alcohol_24_70"]);if(alcohol2470>0)checks.push({key:"alcohol_24_70_total",label:"Alcohol 24–70%",value:alcohol2470,unit:"ml",limit:5000,status:alcohol2470<=5000?"ok":"blocked",message:alcohol2470<=5000?`Total ${(alcohol2470/1000).toFixed(2)} L de 5 L FAA.`:`Total ${(alcohol2470/1000).toFixed(2)} L: supera 5 L FAA.`,sources:sourceRows(["FAA_ALCOHOL","TSA_ALCOHOL"])});
 const alcoholAll=vol(["alcohol_under24","alcohol_24_70"]);if(alcoholAll>0)checks.push({key:"alcohol_customs",label:"Alcohol / franquicia aduanera",value:alcoholAll,unit:"ml",limit:1000,status:alcoholAll<=1000?"ok":"declare",message:alcoholAll<=1000?`Total ${(alcoholAll/1000).toFixed(2)} L dentro de la referencia general de 1 L.`:`Total ${(alcoholAll/1000).toFixed(2)} L; ${(Math.max(0,alcoholAll-1000)/1000).toFixed(2)} L exceden 1 L y deben declararse, con posible arancel/impuesto.`,sources:sourceRows(["CBP_ALCOHOL","CBP_DUTY"])});
 const toiletryVol=vol(["toiletry_liquid","toiletry_aerosol"]),toiletryMass=mass(["toiletry_liquid","toiletry_aerosol"]);if(toiletryVol||toiletryMass)checks.push({key:"toiletry_total",label:"Artículos medicinales/de tocador",value:{ml:toiletryVol,g:toiletryMass},limit:{ml:2000,g:2000},status:toiletryVol<=2000&&toiletryMass<=2000?"ok":"blocked",message:toiletryVol<=2000&&toiletryMass<=2000?"Dentro del máximo agregado FAA de 2 L / 2 kg.":"Supera el máximo agregado FAA de 2 L / 2 kg.",sources:sourceRows(["FAA_TOILETRIES"])});
 const cash=evals.filter(e=>e.profileKey==="cash").reduce((s,e)=>s+(e.normalized.unit==="USD"?e.normalized.value:0),0);if(cash>0)checks.push({key:"cash_total",label:"Efectivo e instrumentos monetarios",value:cash,unit:"USD",limit:10000,status:cash>10000?"declare":"ok",message:cash>10000?"Supera $10,000: FinCEN 105 y declaración obligatoria.":"No supera $10,000.",sources:sourceRows(["CBP_CURRENCY"])});
 const large=evals.filter(e=>e.profileKey==="power_bank_160"&&e.normalized.unit==="Wh"&&e.normalized.value>100&&e.normalized.value<=160).length;if(large)checks.push({key:"battery_101_160_count",label:"Baterías 101–160 Wh",value:large,unit:"count",limit:2,status:large<=2?"conditional":"blocked",message:large<=2?"Aprobación de aerolínea; máximo dos repuestos.":"Supera dos baterías de repuesto 101–160 Wh.",sources:sourceRows(["FAA_BATTERIES"])});
 const cigarettes=evals.filter(e=>e.profileKey==="tobacco_cigarette").reduce((s,e)=>s+(e.normalized.unit==="count"?e.normalized.value:0),0);if(cigarettes)checks.push({key:"cigarettes_total",label:"Cigarrillos",value:cigarettes,unit:"count",limit:200,status:cigarettes<=200?"conditional":"declare",message:cigarettes<=200?"Dentro de la referencia de exención de hasta 200 cigarrillos para viajeros elegibles.":"Supera 200 cigarrillos; puede exceder la exención personal y requiere tratamiento aduanero adicional.",sources:sourceRows(["CBP_TOBACCO"])});
 const cigars=evals.filter(e=>e.profileKey==="tobacco_cigar").reduce((s,e)=>s+(e.normalized.unit==="count"?e.normalized.value:0),0);if(cigars)checks.push({key:"cigars_total",label:"Puros",value:cigars,unit:"count",limit:100,status:cigars<=100?"conditional":"declare",message:cigars<=100?"Dentro de la referencia de hasta 100 puros para viajeros elegibles.":"Supera 100 puros; puede exceder la exención personal.",sources:sourceRows(["CBP_TOBACCO"])});
 return checks;}
