import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.112.4/+esm';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './config.js';

const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true }
});

const $ = id => document.getElementById(id);
const state = {
  session:null,user:null,profile:null,isAdmin:false,view:'dashboard',tripFilter:'all',catalogFilter:'all',
  trips:[],allItems:[],catalog:[],selectedTrip:null,bags:[],items:[],documents:[],adminCatalog:[],adminRules:[],adminSources:[],wizardStep:1
};
const decisionRank={prohibited:5,restricted:4,review:3,allowed_declare:2,allowed:1};
const riskRank={high:4,review:3,medium:2,low:1};

function esc(value=''){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function fmtDate(v,mode='short'){
  if(!v)return '—'; const d=new Date(`${v}T12:00:00`);
  if(mode==='day')return d.toLocaleDateString('es-HN',{day:'2-digit'});
  if(mode==='month')return d.toLocaleDateString('es-HN',{month:'short'}).replace('.','').toUpperCase();
  if(mode==='full')return d.toLocaleDateString('es-HN',{day:'2-digit',month:'short',year:'numeric'}).replace('.','');
  return d.toLocaleDateString('es-HN',{day:'2-digit',month:'short',year:'2-digit'}).replace('.','');
}
function daysBetween(a,b){if(!a||!b)return 0;return Math.max(0,Math.round((Date.parse(`${b}T00:00:00Z`)-Date.parse(`${a}T00:00:00Z`))/86400000));}
function daysUntil(v){if(!v)return null;const today=new Date();today.setHours(0,0,0,0);const target=new Date(`${v}T00:00:00`);return Math.ceil((target-today)/86400000);}
function initials(value='US'){return value.split(/\s|@/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'US';}
function decisionLabel(v){return ({allowed:'Permitido',allowed_declare:'Permitido con declaración',restricted:'Condicionado',prohibited:'No permitido',review:'Revisar'})[v]||'Revisar';}
function riskLabel(v){return ({low:'Bajo',medium:'Medio',high:'Alto',review:'Revisar'})[v]||'Revisar';}
function riskClass(v){return ['low','medium','high','review'].includes(v)?v:'review';}
function statusLabel(v){return ({planned:'Próximo',active:'En viaje',completed:'Completado',cancelled:'Cancelado'})[v]||v;}
function purposeLabel(v){return ({tourism:'Turismo',family:'Visita familiar',business:'Negocios',study:'Estudio',other:'Otro'})[v]||'Viaje';}
function tripCode(t){return t.entry_airport||'USA';}
function showToast(message,type='info'){$('toast').textContent=message;$('toast').className=`toast ${type}`;clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>$('toast').classList.add('hidden'),5000);}
function handleError(error){console.error(error);showToast(error?.message||'Ocurrió un error inesperado.','error');}
function openDialog(id){const d=$(id);if(d&&!d.open)d.showModal();}
function closeDialog(id){const d=$(id);if(d?.open)d.close();}
function currentCatalogByText(text){const q=text.trim().toLowerCase();return state.catalog.find(i=>i.canonical_name_es.toLowerCase()===q||i.canonical_name_en.toLowerCase()===q||(i.aliases||[]).some(a=>a.toLowerCase()===q));}
function currentUserName(){const raw=state.profile?.display_name||state.user?.email?.split('@')[0]||'Viajero';return raw.length>18?'Viajero':raw;}
function itemName(i){return i.catalog_items?.canonical_name_es||i.custom_name||'Artículo';}
function itemEmoji(i){const n=(i.canonical_name_es||i.catalog_items?.canonical_name_es||'').toLowerCase();if(n.includes('café'))return '☕';if(n.includes('cerdo'))return '🥩';if(n.includes('fruta')||n.includes('mango')||n.includes('aguac'))return '🥭';if(n.includes('planta'))return '🌿';if(n.includes('ques')||n.includes('leche'))return '🧀';if(n.includes('pollo')||n.includes('gallina'))return '🍗';if(n.includes('pesc'))return '🐟';if(n.includes('pan')||n.includes('tortilla'))return '🥖';return '◈';}

async function ensureProfile(){
  const {data,error}=await supabase.from('profiles').select('*').eq('user_id',state.user.id).maybeSingle();
  if(error)throw error;
  if(data){state.profile=data;return;}
  const display=state.user.email?.split('@')[0]||'Viajero';
  const ins=await supabase.from('profiles').insert({user_id:state.user.id,display_name:display}).select('*').single();
  if(ins.error)throw ins.error; state.profile=ins.data;
}
async function detectAdmin(){const {data,error}=await supabase.from('admin_users').select('user_id').eq('user_id',state.user.id).maybeSingle();if(error)throw error;state.isAdmin=!!data;}
async function loadCatalog(){const {data,error}=await supabase.from('catalog_items').select('*').eq('active',true).order('canonical_name_es');if(error)throw error;state.catalog=data||[];$('catalogDatalist').innerHTML=state.catalog.map(i=>`<option value="${esc(i.canonical_name_es)}">${esc(i.category)} · ${esc(i.subcategory||'')}</option>`).join('');}
async function loadTrips(){const {data,error}=await supabase.from('trips').select('*').eq('user_id',state.user.id).order('departure_date',{ascending:false});if(error)throw error;state.trips=data||[];if(state.selectedTrip)state.selectedTrip=state.trips.find(t=>t.id===state.selectedTrip.id)||null;}
async function loadAllItems(){const {data,error}=await supabase.from('trip_items').select('id,trip_id,computed_decision,computed_risk,declared').eq('user_id',state.user.id);if(error)throw error;state.allItems=data||[];}
async function loadBaseData(){await Promise.all([loadCatalog(),loadTrips(),loadAllItems()]);}

async function initAuthenticated(session){
  state.session=session;state.user=session.user;
  $('authView').classList.add('hidden');$('appView').classList.remove('hidden');
  await Promise.all([ensureProfile(),detectAdmin()]);await loadBaseData();
  $('avatarInitials').textContent=initials(currentUserName());
  $('adminNavItem').classList.toggle('hidden',!state.isAdmin);$('profileNavItem').classList.toggle('hidden',state.isAdmin);
  renderAll();switchView('dashboard');
}
function initSignedOut(){state.session=null;state.user=null;state.profile=null;state.isAdmin=false;state.selectedTrip=null;$('authView').classList.remove('hidden');$('appView').classList.add('hidden');}

function tripItems(tripId){return state.allItems.filter(i=>i.trip_id===tripId);}
function tripScore(t,items=tripItems(t.id)){
  const checks=[!!t.departure_date,!!t.return_date,!!t.airline,!!t.entry_airport,!!t.purpose];
  let doc=Math.round(checks.filter(Boolean).length/checks.length*100),stay=100;
  if(t.admit_until&&t.return_date&&t.return_date>t.admit_until)stay=20;
  let penalty=0;for(const i of items){penalty+=({prohibited:40,restricted:18,review:10,allowed_declare:i.declared?0:6,allowed:0})[i.computed_decision]||0;}
  return Math.max(0,Math.round((doc+stay+Math.max(0,100-penalty)+Math.max(0,100-penalty))/4));
}
function computeSelectedScores(){
  const t=state.selectedTrip;if(!t)return null;
  const checks=[!!t.departure_date,!!t.return_date,!!t.airline,!!t.entry_airport,!!t.purpose];
  const documentScore=Math.round(checks.filter(Boolean).length/checks.length*100);let stayScore=100;const blockers=[];
  if(t.admit_until&&t.return_date&&t.return_date>t.admit_until){stayScore=20;blockers.push({level:'high',text:'El regreso previsto supera la fecha Admit Until registrada.'});}
  let penalty=0;for(const i of state.items){let p=({prohibited:42,restricted:20,review:12,allowed_declare:0,allowed:0})[i.computed_decision]||0;if(i.computed_decision==='allowed_declare'&&!i.declared)p+=8;penalty+=p;if(['prohibited','restricted','review'].includes(i.computed_decision))blockers.push({level:i.computed_decision==='prohibited'?'high':'medium',text:`${itemName(i)} · ${decisionLabel(i.computed_decision)}`});}
  const cbpScore=Math.max(0,100-penalty),usdaScore=Math.max(0,100-penalty),readiness=Math.round((documentScore+stayScore+cbpScore+usdaScore)/4);
  return {documentScore,stayScore,cbpScore,usdaScore,tsaScore:0,readiness,blockers};
}
function nextTrip(){const today=new Date().toISOString().slice(0,10);return [...state.trips].filter(t=>t.status!=='cancelled'&&t.departure_date>=today).sort((a,b)=>a.departure_date.localeCompare(b.departure_date))[0]||state.trips.find(t=>t.status==='active')||null;}
function renderPageHead(title,subtitle='',right=''){return `<div class="page-head"><div><p class="eyebrow">${esc(subtitle)}</p><h1>${esc(title)}</h1></div>${right}</div>`;}

function renderDashboard(){
  const t=nextTrip();const score=t?tripScore(t):0;const d=t?daysUntil(t.departure_date):null;const alerts=state.allItems.filter(i=>['prohibited','restricted','review'].includes(i.computed_decision));
  $('bellDot').classList.toggle('hidden',alerts.length===0);
  const hero=t?`<div class="travel-hero"><div class="travel-hero__content"><div class="trip-label"><span>Próximo viaje</span><span class="countdown">${d===0?'Hoy':d>0?`En ${d} días`:'En curso'}</span></div><div class="route"><span>SAP</span><i class="ico ico-plane"></i><span>${esc(tripCode(t))}</span></div><div class="trip-meta"><span>${fmtDate(t.departure_date,'full')}</span><span>${esc(t.airline||'Aerolínea pendiente')}</span><span>${esc(t.flight_number||'')}</span></div></div></div>`:`<div class="travel-hero"><div class="travel-hero__content"><div class="trip-label"><span>Próximo viaje</span></div><div class="empty-state"><i class="ico ico-plane"></i><h3>Tu próximo viaje empieza aquí</h3><p>Crea un expediente y EntrySafe organizará los datos, artículos y alertas del viaje.</p><button class="primary-inline" data-action="new-trip">Crear viaje</button></div></div></div>`;
  const scoreCard=`<div class="score-card"><div><p class="eyebrow">Tu estado general</p><h3>${t?'Preparación del próximo viaje':'Sin viaje activo'}</h3><p>${t?'Sigue las alertas para llegar al 100%.':'Crea un viaje para comenzar.'}</p></div><div class="score-ring" style="--score:${score}"><div><strong>${score}</strong><span>Preparación</span></div></div></div>`;
  $('dashboardView').innerHTML=`${renderPageHead(`Hola, ${currentUserName()}`,state.isAdmin?'Centro privado · Administrador':'Resumen general',state.isAdmin?'<span class="admin-pill"><i class="ico ico-crown"></i> Administrador</span>':'')}<div class="hero-grid">${hero}${scoreCard}</div>
  <div class="metric-grid"><div class="metric-card"><i class="ico ico-plane"></i><strong>${state.trips.length}</strong><span>Viajes</span></div><div class="metric-card"><i class="ico ico-chart"></i><strong>${state.trips.reduce((n,x)=>n+daysBetween(x.departure_date,x.return_date),0)}</strong><span>Días planificados</span></div><div class="metric-card"><i class="ico ico-bag"></i><strong>${state.allItems.length}</strong><span>Artículos</span></div><div class="metric-card"><i class="ico ico-alert"></i><strong>${alerts.length}</strong><span>Alertas activas</span></div></div>
  <div class="section-card"><div class="section-head"><h2>Alertas importantes</h2><button data-view="catalog">Abrir catálogo</button></div>${alerts.length?alerts.slice(0,3).map(i=>`<div class="alert-card"><i class="ico ico-alert"></i><div><strong>${esc(decisionLabel(i.computed_decision))}</strong><small>Hay un artículo que requiere tu atención antes del viaje.</small></div></div>`).join(''):'<div class="alert-card" style="background:#0d3025;border-color:#225c43;color:#7addaa"><i class="ico ico-check"></i><div><strong>Sin alertas críticas</strong><small>Tu registro personal no tiene bloqueos activos.</small></div></div>'}</div>
  <div class="section-card"><div class="section-head"><h2>Cobertura y autoridades</h2><span></span></div><div class="authority-grid"><div class="authority"><b>USDA / APHIS</b><span>ACTIVA</span></div><div class="authority"><b>CBP / Aduanas</b><span>ACTIVA</span></div><div class="authority"><b>TSA</b><span style="color:#e0b65a">EN EXPANSIÓN</span></div><div class="authority"><b>FDA / FWS</b><span>REFERENCIAS</span></div></div></div>`;
  bindDynamicActions($('dashboardView'));
}

function renderTrips(){
  let trips=[...state.trips];if(state.tripFilter!=='all')trips=trips.filter(t=>t.status===state.tripFilter);
  $('tripsView').innerHTML=`${renderPageHead('Mis viajes','Expedientes personales','<button class="primary-inline" data-action="new-trip">+ Nuevo viaje</button>')}<div class="filter-row"><button class="filter-chip ${state.tripFilter==='all'?'active':''}" data-trip-filter="all">Todos</button><button class="filter-chip ${state.tripFilter==='planned'?'active':''}" data-trip-filter="planned">Próximos</button><button class="filter-chip ${state.tripFilter==='active'?'active':''}" data-trip-filter="active">En curso</button><button class="filter-chip ${state.tripFilter==='completed'?'active':''}" data-trip-filter="completed">Completados</button></div><div class="trip-list">${trips.length?trips.map(t=>{const s=tripScore(t);const d=daysUntil(t.departure_date);return `<article class="trip-card" data-open-trip="${t.id}"><div class="date-tile"><strong>${fmtDate(t.departure_date,'day')}</strong><span>${fmtDate(t.departure_date,'month')}</span></div><div class="trip-card__main"><h3>SAP → ${esc(tripCode(t))}</h3><p>${esc(t.airline||'Aerolínea pendiente')} ${esc(t.flight_number||'')}</p><div class="status-line"><span class="status-badge ${t.status==='completed'?'low':'review'}">${esc(statusLabel(t.status))}</span>${d!==null&&d>=0&&t.status==='planned'?`<span class="status-badge review">En ${d} días</span>`:''}</div></div><div class="mini-score" style="--score:${s}"><b>${s}</b></div></article>`}).join(''):`<div class="empty-state"><i class="ico ico-plane"></i><h3>No hay viajes en esta sección</h3><p>Crea tu primer expediente para comenzar a llevar el historial.</p><button class="primary-inline" data-action="new-trip">Crear viaje</button></div>`}</div>`;
  $('tripsView').querySelectorAll('[data-trip-filter]').forEach(b=>b.addEventListener('click',()=>{state.tripFilter=b.dataset.tripFilter;renderTrips();}));
  $('tripsView').querySelectorAll('[data-open-trip]').forEach(b=>b.addEventListener('click',()=>selectTrip(b.dataset.openTrip).catch(handleError)));bindDynamicActions($('tripsView'));
}

function renderCurrentTrip(){
  const t=state.selectedTrip;if(!t){$('currentTripView').innerHTML=`${renderPageHead('Viaje actual','Expediente inteligente')}<div class="empty-state section-card"><i class="ico ico-plane"></i><h3>Selecciona un viaje</h3><p>Abre uno desde “Viajes” o crea un nuevo expediente.</p><button class="primary-inline" data-view="trips">Ver mis viajes</button></div>`;bindDynamicActions($('currentTripView'));return;}
  const s=computeSelectedScores();const d=daysUntil(t.departure_date);const bad=state.items.filter(i=>['prohibited','restricted','review'].includes(i.computed_decision));const declared=state.items.filter(i=>i.declared).length;
  $('currentTripView').innerHTML=`${renderPageHead('Viaje actual','Expediente de viaje',`<span class="status-badge ${s.readiness>=85?'low':'review'}">${s.readiness>=85?'Riesgo bajo':'Revisar'}</span>`)}
  <div class="current-hero"><p class="eyebrow">${esc(purposeLabel(t.purpose))}</p><h1>SAP → ${esc(tripCode(t))}</h1><div class="trip-meta"><span>${fmtDate(t.departure_date,'full')} – ${fmtDate(t.return_date,'full')}</span><span>${d!==null&&d>=0?`En ${d} días`:statusLabel(t.status)}</span></div></div>
  <div class="section-card"><div class="section-head"><h2>Score de cumplimiento</h2><strong>${s.readiness}/100</strong></div><div class="progress-shell"><i style="width:${s.readiness}%"></i></div><p style="color:#7792a7;font-size:11px;margin:9px 0 0">${s.blockers.length?`${s.blockers.length} punto(s) requieren revisión.`:'Excelente. No hay bloqueos detectados en la cobertura cargada.'}</p></div>
  <div class="journey-grid"><button class="journey-action" data-current-section="summary"><i class="ico ico-chart"></i><div><b>Resumen del viaje</b><span>Vuelo, fechas y preparación</span></div><span class="state-ok">✓</span></button><button class="journey-action" data-current-section="luggage"><i class="ico ico-bag"></i><div><b>Equipaje y artículos</b><span>${state.items.length} artículos · ${state.bags.length} maletas</span></div><span class="${bad.length?'state-warn':'state-ok'}">${bad.length?bad.length:'✓'}</span></button><button class="journey-action" data-current-section="declaration"><i class="ico ico-doc"></i><div><b>Declaración CBP</b><span>${declared} marcados como declarados</span></div><span class="${state.items.length&&declared<state.items.filter(i=>i.computed_decision==='allowed_declare').length?'state-warn':'state-ok'}">›</span></button><button class="journey-action" data-current-section="documents"><i class="ico ico-shield"></i><div><b>Documentos</b><span>${state.documents.length} documentos privados</span></div><span class="state-ok">›</span></button></div>
  <div id="currentSection"></div>`;
  $('currentTripView').querySelectorAll('[data-current-section]').forEach(b=>b.addEventListener('click',()=>renderCurrentSection(b.dataset.currentSection)));renderCurrentSection('summary');
}
function renderCurrentSection(section){const host=$('currentSection');if(!host||!state.selectedTrip)return;const s=computeSelectedScores();
  if(section==='summary'){host.innerHTML=`<div class="section-card"><div class="section-head"><h2>Estado del expediente</h2><button id="saveSnapshotBtn">Guardar balance</button></div><div class="bag-summary"><div><b>${s.documentScore}</b><span>Documentación</span></div><div><b>${s.cbpScore}</b><span>CBP</span></div><div><b>${s.usdaScore}</b><span>USDA</span></div></div>${s.blockers.length?`<div style="margin-top:12px;display:grid;gap:7px">${s.blockers.map(x=>`<div class="alert-card"><i class="ico ico-alert"></i><div><strong>${x.level==='high'?'Atención alta':'Revisar'}</strong><small>${esc(x.text)}</small></div></div>`).join('')}</div>`:''}<div style="margin-top:12px;display:flex;gap:8px"><button id="completeTripBtn" class="primary-inline">Marcar completado</button></div></div>`;$('saveSnapshotBtn')?.addEventListener('click',()=>saveSnapshot().catch(handleError));$('completeTripBtn')?.addEventListener('click',()=>completeTrip().catch(handleError));return;}
  if(section==='luggage'){host.innerHTML=`<div class="section-card"><div class="section-head"><h2>Equipaje y artículos</h2><span><button data-action="new-bag">+ Maleta</button> <button data-action="new-item">+ Artículo</button></span></div><div class="bag-chips">${state.bags.length?state.bags.map(b=>`<span class="bag-chip">${esc(b.label)} · ${esc(b.bag_type)}</span>`).join(''):'<span style="color:#708aa1;font-size:11px">Sin maletas registradas.</span>'}</div><div class="item-list" style="margin-top:13px">${state.items.length?state.items.map(i=>`<article class="item-row"><div><h4>${esc(itemName(i))}</h4><span class="status-badge ${riskClass(i.computed_risk)}">${esc(decisionLabel(i.computed_decision))} · riesgo ${esc(riskLabel(i.computed_risk))}</span><p>${esc(i.regulatory_rules?.explanation||'Sin regla específica; requiere revisión.')}</p>${i.regulatory_rules?.regulatory_sources?`<a class="source-link" href="${esc(i.regulatory_rules.regulatory_sources.url)}" target="_blank" rel="noopener">${esc(i.regulatory_rules.regulatory_sources.agency)} · fuente oficial</a>`:''}</div><div class="item-actions"><button class="tiny-btn" data-declare="${i.id}">${i.declared?'Declarado':'Declarar'}</button><button class="tiny-btn danger" data-delete-item="${i.id}">×</button></div></article>`).join(''):'<div class="empty-state"><i class="ico ico-bag"></i><h3>Tu equipaje está vacío</h3><p>Agrega productos para evaluar las reglas cargadas.</p><button class="primary-inline" data-action="new-item">Agregar artículo</button></div>`}</div></div>`;host.querySelectorAll('[data-declare]').forEach(b=>b.addEventListener('click',()=>toggleDeclared(b.dataset.declare).catch(handleError)));host.querySelectorAll('[data-delete-item]').forEach(b=>b.addEventListener('click',()=>deleteItem(b.dataset.deleteItem).catch(handleError)));bindDynamicActions(host);return;}
  if(section==='declaration'){host.innerHTML=`<div class="section-card"><div class="section-head"><h2>Declaración CBP</h2><button data-action="open-declaration">Ver resumen en inglés</button></div>${state.items.length?`<div class="item-list">${state.items.map(i=>`<div class="item-row"><div><h4>${esc(itemName(i))}</h4><p>${esc(decisionLabel(i.computed_decision))}</p></div><span class="status-badge ${i.declared?'low':'review'}">${i.declared?'Declarado':'Pendiente'}</span></div>`).join('')}</div>`:'<div class="empty-state">No hay artículos para declarar.</div>'}</div>`;bindDynamicActions(host);return;}
  if(section==='documents'){host.innerHTML=`<div class="section-card"><div class="section-head"><h2>Documentos privados</h2><button data-action="new-document">+ Documento</button></div><div class="trip-list">${state.documents.length?state.documents.map(d=>`<div class="trip-card" style="grid-template-columns:52px 1fr auto"><div class="date-tile"><i class="ico ico-doc"></i></div><div class="trip-card__main"><h3>${esc(d.document_type.toUpperCase())}</h3><p>${esc(d.masked_identifier||'Sin identificador')} ${d.expires_on?'· vence '+fmtDate(d.expires_on,'full'):''}</p></div><span class="status-badge low">Privado</span></div>`).join(''):'<div class="empty-state"><i class="ico ico-doc"></i><h3>Sin documentos</h3><p>Guarda metadatos y archivos privados de pasaporte, visa, boleto o I-94.</p></div>`}</div></div>`;bindDynamicActions(host);}
}

function renderCatalog(){const categories=[...new Set(state.catalog.map(i=>i.category).filter(Boolean))];$('catalogView').innerHTML=`${renderPageHead('Catálogo regulatorio','Información oficial')}<div class="catalog-toolbar"><div class="catalog-search"><i class="ico ico-search"></i><input id="catalogSearch" placeholder="Buscar alimento, planta o artículo…"></div></div><div class="filter-row"><button class="filter-chip ${state.catalogFilter==='all'?'active':''}" data-cat-filter="all">Todos</button>${categories.slice(0,7).map(c=>`<button class="filter-chip ${state.catalogFilter===c?'active':''}" data-cat-filter="${esc(c)}">${esc(c)}</button>`).join('')}</div><div id="catalogList" class="catalog-list"></div>`;$('catalogSearch').addEventListener('input',renderCatalogRows);$('catalogView').querySelectorAll('[data-cat-filter]').forEach(b=>b.addEventListener('click',()=>{state.catalogFilter=b.dataset.catFilter;renderCatalog();}));renderCatalogRows();}
function renderCatalogRows(){const host=$('catalogList');if(!host)return;const q=$('catalogSearch')?.value.trim().toLowerCase()||'';let rows=state.catalog;if(state.catalogFilter!=='all')rows=rows.filter(i=>i.category===state.catalogFilter);rows=rows.filter(i=>!q||[i.canonical_name_es,i.canonical_name_en,i.category,i.subcategory,...(i.aliases||[])].filter(Boolean).some(v=>String(v).toLowerCase().includes(q))).slice(0,100);host.innerHTML=rows.length?rows.map(i=>`<article class="catalog-card"><div><h3>${esc(i.canonical_name_es)}</h3><p>${esc(i.canonical_name_en)} · ${esc(i.subcategory||i.category)}</p><span class="status-badge ${riskClass(i.default_risk)}"><i class="risk-dot ${riskClass(i.default_risk)}"></i> Riesgo ${esc(riskLabel(i.default_risk))}</span></div><div class="catalog-icon">${itemEmoji(i)}</div></article>`).join(''):'<div class="empty-state"><i class="ico ico-search"></i><h3>Sin coincidencias</h3><p>Prueba con otro nombre o categoría.</p></div>';}

async function loadAdminData(){if(!state.isAdmin)return;const [c,r,s,t,i]=await Promise.all([supabase.from('catalog_items').select('*').order('canonical_name_es'),supabase.from('regulatory_rules').select('id,decision,risk_level,rule_version,active,catalog_item_id,last_verified_at').order('last_verified_at',{ascending:false}),supabase.from('regulatory_sources').select('*').order('last_verified_at',{ascending:false}),supabase.from('trips').select('id,status',{count:'exact'}),supabase.from('trip_items').select('id,computed_decision',{count:'exact'})]);for(const x of [c,r,s,t,i])if(x.error)throw x.error;state.adminCatalog=c.data||[];state.adminRules=r.data||[];state.adminSources=s.data||[];state.adminTripCount=t.count??(t.data||[]).length;state.adminItemCount=i.count??(i.data||[]).length;}
async function renderAdmin(){if(!state.isAdmin){$('adminView').innerHTML=`<div class="empty-state"><i class="ico ico-lock"></i><h3>Acceso restringido</h3></div>`;return;}await loadAdminData();const activeRules=state.adminRules.filter(r=>r.active).length,alerts=state.adminRules.filter(r=>['prohibited','restricted'].includes(r.decision)&&r.active).length;$('adminView').innerHTML=`<div class="admin-hero"><div><p class="eyebrow">Centro de control</p><h1>Administrador</h1><p>Gestión regulatoria, auditoría y estado del sistema.</p></div><div class="admin-crown"><i class="ico ico-crown"></i></div></div><div class="admin-metrics"><div class="admin-metric"><strong>${activeRules}</strong><span>Reglas activas</span></div><div class="admin-metric"><strong>${state.adminCatalog.length}</strong><span>Artículos catálogo</span></div><div class="admin-metric"><strong>${state.adminSources.length}</strong><span>Fuentes oficiales</span></div><div class="admin-metric"><strong>${alerts}</strong><span>Reglas restrictivas</span></div></div><div class="section-card"><div class="section-head"><h2>Gestión</h2><button data-action="admin-add-item">+ Artículo</button></div><div class="admin-actions"><button class="admin-action" data-admin-panel="catalog"><b>Catálogo regulatorio</b><span>Agregar, activar y organizar artículos.</span></button><button class="admin-action" data-admin-panel="rules"><b>Regulaciones</b><span>Revisar decisiones y versiones activas.</span></button><button class="admin-action" data-admin-panel="sources"><b>Fuentes oficiales</b><span>USDA, CBP y referencias verificadas.</span></button><button class="admin-action" data-admin-panel="system"><b>Actividad del sistema</b><span>${state.adminTripCount} viajes · ${state.adminItemCount} artículos registrados.</span></button></div></div><div id="adminPanel"></div>`;$('adminView').querySelectorAll('[data-admin-panel]').forEach(b=>b.addEventListener('click',()=>renderAdminPanel(b.dataset.adminPanel)));bindDynamicActions($('adminView'));renderAdminPanel('catalog');}
function renderAdminPanel(panel){const host=$('adminPanel');if(!host)return;if(panel==='catalog'){host.innerHTML=`<div class="section-card"><div class="section-head"><h2>Catálogo</h2><span>${state.adminCatalog.length} registros</span></div><div class="admin-table">${state.adminCatalog.slice(0,40).map(i=>`<div class="admin-row"><div><b>${esc(i.canonical_name_es)}</b><span>${esc(i.category)} · riesgo ${esc(riskLabel(i.default_risk))}</span></div><button class="tiny-btn" data-toggle-catalog="${i.id}" data-active="${i.active}">${i.active?'Activo':'Inactivo'}</button></div>`).join('')}</div></div>`;host.querySelectorAll('[data-toggle-catalog]').forEach(b=>b.addEventListener('click',()=>toggleCatalogActive(b.dataset.toggleCatalog,b.dataset.active==='true').catch(handleError)));return;}if(panel==='rules'){host.innerHTML=`<div class="section-card"><div class="section-head"><h2>Reglas regulatorias</h2><span>${state.adminRules.length} reglas</span></div><div class="admin-table">${state.adminRules.slice(0,40).map(r=>`<div class="admin-row"><div><b>${esc(r.rule_version)}</b><span>${esc(decisionLabel(r.decision))} · riesgo ${esc(riskLabel(r.risk_level))}</span></div><span class="status-badge ${r.active?'low':'review'}">${r.active?'Activa':'Inactiva'}</span></div>`).join('')}</div></div>`;return;}if(panel==='sources'){host.innerHTML=`<div class="section-card"><div class="section-head"><h2>Fuentes oficiales</h2><span>${state.adminSources.length}</span></div><div class="admin-table">${state.adminSources.map(s=>`<div class="admin-row"><div><b>${esc(s.agency)} · ${esc(s.title)}</b><span>Verificada ${new Date(s.last_verified_at).toLocaleDateString('es-HN')}</span></div><a class="source-link" href="${esc(s.url)}" target="_blank" rel="noopener">Abrir</a></div>`).join('')}</div></div>`;return;}host.innerHTML=`<div class="section-card"><div class="section-head"><h2>Resumen del sistema</h2></div><div class="bag-summary"><div><b>${state.adminTripCount}</b><span>Viajes totales</span></div><div><b>${state.adminItemCount}</b><span>Artículos usados</span></div><div><b>${state.adminRules.length}</b><span>Reglas registradas</span></div></div></div>`;}

function renderProfile(){$('profileView').innerHTML=`${renderPageHead('Perfil y seguridad','Cuenta privada')}<div class="profile-card"><div class="profile-avatar">${esc(initials(currentUserName()))}</div><h1>${esc(currentUserName())}</h1><p>${esc(state.user.email||'')}</p>${state.isAdmin?'<span class="admin-pill"><i class="ico ico-crown"></i> Administrador</span>':''}<div class="profile-actions"><button class="profile-action"><i class="ico ico-shield"></i><div><b>Privacidad</b><span>Datos protegidos mediante RLS y almacenamiento privado.</span></div></button><button class="profile-action"><i class="ico ico-doc"></i><div><b>Idioma</b><span>Español · Honduras</span></div></button><button id="signOutBtn" class="profile-action danger"><i class="ico ico-close"></i><div><b>Cerrar sesión</b><span>Salir de EntrySafe en este dispositivo.</span></div></button></div></div>`;$('signOutBtn').addEventListener('click',signOut);}

function renderAll(){renderDashboard();renderTrips();renderCurrentTrip();renderCatalog();renderProfile();if(state.isAdmin)renderAdmin().catch(handleError);}
function switchView(name){
  if(name==='admin'&&!state.isAdmin)name='profile';state.view=name;
  document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));$(`${name}View`)?.classList.remove('hidden');
  document.querySelectorAll('.nav-item[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));
  if(name==='dashboard')renderDashboard();if(name==='trips')renderTrips();if(name==='currentTrip')renderCurrentTrip();if(name==='catalog')renderCatalog();if(name==='profile')renderProfile();if(name==='admin')renderAdmin().catch(handleError);
  window.scrollTo({top:0,behavior:'smooth'});
}
function bindDynamicActions(root=document){root.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));root.querySelectorAll('[data-action="new-trip"]').forEach(b=>b.addEventListener('click',()=>startTripWizard()));root.querySelectorAll('[data-action="new-item"]').forEach(b=>b.addEventListener('click',()=>openDialog('itemDialog')));root.querySelectorAll('[data-action="new-bag"]').forEach(b=>b.addEventListener('click',()=>openDialog('bagDialog')));root.querySelectorAll('[data-action="new-document"]').forEach(b=>b.addEventListener('click',()=>openDialog('documentDialog')));root.querySelectorAll('[data-action="open-declaration"]').forEach(b=>b.addEventListener('click',openDeclaration));root.querySelectorAll('[data-action="admin-add-item"]').forEach(b=>b.addEventListener('click',()=>openDialog('adminCatalogDialog')));}

async function selectTrip(id){
  state.selectedTrip=state.trips.find(t=>t.id===id)||null;if(!state.selectedTrip)return;
  const [bagsRes,itemsRes,docsRes]=await Promise.all([
    supabase.from('trip_bags').select('*').eq('trip_id',id).eq('user_id',state.user.id).order('created_at'),
    supabase.from('trip_items').select('*, catalog_items(canonical_name_es,canonical_name_en,category,subcategory), regulatory_rules(id,explanation,traveler_action,declaration_required,regulatory_sources(title,url,agency))').eq('trip_id',id).eq('user_id',state.user.id).order('created_at'),
    supabase.from('trip_documents').select('*').eq('trip_id',id).eq('user_id',state.user.id).order('created_at',{ascending:false})
  ]);for(const r of [bagsRes,itemsRes,docsRes])if(r.error)throw r.error;state.bags=bagsRes.data||[];state.items=itemsRes.data||[];state.documents=docsRes.data||[];updateItemBagOptions();await loadAllItems();renderDashboard();renderTrips();renderCurrentTrip();switchView('currentTrip');
}
function updateItemBagOptions(){$('itemBag').innerHTML='<option value="">Sin asignar</option>'+state.bags.map(b=>`<option value="${b.id}">${esc(b.label)}</option>`).join('');}

function startTripWizard(){state.wizardStep=1;$('tripWizardForm').reset();showWizardStep();openDialog('tripWizard');}
function showWizardStep(){document.querySelectorAll('.wizard-step').forEach(x=>x.classList.toggle('hidden',Number(x.dataset.step)!==state.wizardStep));document.querySelectorAll('[data-step-dot]').forEach(x=>x.classList.toggle('active',Number(x.dataset.stepDot)<=state.wizardStep));$('wizardBackBtn').classList.toggle('hidden',state.wizardStep===1);$('wizardNextBtn').classList.toggle('hidden',state.wizardStep===3);$('wizardSaveBtn').classList.toggle('hidden',state.wizardStep!==3);}
function nextWizard(){if(state.wizardStep===1&&!$('departureDate').value){showToast('Selecciona la fecha de salida.','error');return;}if(state.wizardStep<3){state.wizardStep++;showWizardStep();}}
function backWizard(){if(state.wizardStep>1){state.wizardStep--;showWizardStep();}}
async function createTrip(e){e.preventDefault();const dep=$('departureDate').value,ret=$('returnDate').value||null;if(ret&&ret<dep){showToast('El regreso no puede ser anterior a la salida.','error');return;}const payload={user_id:state.user.id,origin_country:'HN',destination_country:'US',departure_date:dep,return_date:ret,entry_airport:$('entryAirport').value.trim().toUpperCase()||null,airline:$('airline').value.trim()||null,flight_number:$('flightNumber').value.trim()||null,booking_reference:$('bookingReference').value.trim()||null,purpose:$('purpose').value,notes:$('tripNotes').value.trim()||null,status:'planned'};const {data,error}=await supabase.from('trips').insert(payload).select('*').single();if(error)throw error;closeDialog('tripWizard');await loadTrips();renderTrips();showToast('Viaje creado correctamente.','success');await selectTrip(data.id);}
async function addBag(e){e.preventDefault();if(!state.selectedTrip){showToast('Primero selecciona un viaje.','error');return;}const {error}=await supabase.from('trip_bags').insert({trip_id:state.selectedTrip.id,user_id:state.user.id,bag_type:$('bagType').value,label:$('bagLabel').value.trim()});if(error)throw error;closeDialog('bagDialog');e.target.reset();await selectTrip(state.selectedTrip.id);showToast('Maleta agregada.','success');}
function ruleMatches(rule,attrs){const c=rule?.condition_json||{};if(c.must_be_thoroughly_cooked===true&&attrs.cooked_state!=='fully_cooked')return false;if(c.sealed===true&&!attrs.hermetically_sealed)return false;if(c.commercial===true&&!attrs.commercial_packaging)return false;if(c.shelf_stable===true&&!attrs.shelf_stable)return false;return true;}
async function resolveRule(catalogItemId,attrs){if(!catalogItemId)return null;const {data,error}=await supabase.from('regulatory_rules').select('*, regulatory_sources(*)').eq('catalog_item_id',catalogItemId).eq('origin_country','HN').eq('destination_region','US_CONTINENTAL').eq('active',true);if(error)throw error;return (data||[]).filter(r=>ruleMatches(r,attrs)).sort((a,b)=>(decisionRank[b.decision]-decisionRank[a.decision])||(riskRank[b.risk_level]-riskRank[a.risk_level]))[0]||null;}
async function addItem(e){e.preventDefault();if(!state.selectedTrip){showToast('Primero selecciona un viaje.','error');return;}const catalog=currentCatalogByText($('itemSearch').value);const attrs={cooked_state:$('cookedState').value,homemade:$('homemade').checked,commercial_packaging:$('commercialPackaging').checked,hermetically_sealed:$('sealed').checked,shelf_stable:$('shelfStable').checked,contains_meat:$('containsMeat').checked};const rule=await resolveRule(catalog?.id,attrs);const decision=rule?.decision||'review',risk=rule?.risk_level||catalog?.default_risk||'review';const payload={trip_id:state.selectedTrip.id,bag_id:$('itemBag').value||null,user_id:state.user.id,catalog_item_id:catalog?.id||null,custom_name:catalog?null:$('itemSearch').value.trim(),quantity:Number($('itemQuantity').value)||1,...attrs,computed_decision:decision,computed_risk:risk,matched_rule_id:rule?.id||null,rule_version:rule?.rule_version||null};const {error}=await supabase.from('trip_items').insert(payload);if(error)throw error;closeDialog('itemDialog');e.target.reset();$('itemQuantity').value='1';$('cookedState').value='not_applicable';await selectTrip(state.selectedTrip.id);showToast(`Artículo agregado · ${decisionLabel(decision)}`,decision==='prohibited'?'error':'success');renderCurrentSection('luggage');}
async function toggleDeclared(id){const item=state.items.find(i=>i.id===id);if(!item)return;const {error}=await supabase.from('trip_items').update({declared:!item.declared}).eq('id',id).eq('user_id',state.user.id);if(error)throw error;await selectTrip(state.selectedTrip.id);renderCurrentSection('luggage');}
async function deleteItem(id){if(!confirm('¿Eliminar este artículo del viaje?'))return;const {error}=await supabase.from('trip_items').delete().eq('id',id).eq('user_id',state.user.id);if(error)throw error;await selectTrip(state.selectedTrip.id);renderCurrentSection('luggage');}
async function addDocument(e){e.preventDefault();if(!state.selectedTrip){showToast('Primero selecciona un viaje.','error');return;}let storagePath=null;const file=$('documentFile').files?.[0];if(file){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');storagePath=`${state.user.id}/${state.selectedTrip.id}/${crypto.randomUUID()}-${safe}`;const up=await supabase.storage.from('travel-documents').upload(storagePath,file,{upsert:false});if(up.error)throw up.error;}const {error}=await supabase.from('trip_documents').insert({trip_id:state.selectedTrip.id,user_id:state.user.id,document_type:$('documentType').value,masked_identifier:$('maskedIdentifier').value.trim()||null,expires_on:$('documentExpiry').value||null,storage_path:storagePath});if(error)throw error;closeDialog('documentDialog');e.target.reset();await selectTrip(state.selectedTrip.id);showToast('Documento guardado de forma privada.','success');renderCurrentSection('documents');}
function openDeclaration(){if(!state.selectedTrip)return;const list=$('declarationList');list.innerHTML=state.items.length?state.items.map(i=>`<div class="declaration-item"><b>${esc(i.catalog_items?.canonical_name_en||itemName(i))}</b><br><span style="color:#7f99af">${esc(decisionLabel(i.computed_decision))}${i.declared?' · marked declared':''}</span></div>`).join(''):'<div class="empty-state">No registered food or agricultural products.</div>';openDialog('declarationDialog');}
async function saveSnapshot(){const s=computeSelectedScores();if(!s)return;const {error}=await supabase.from('compliance_snapshots').insert({trip_id:state.selectedTrip.id,user_id:state.user.id,document_score:s.documentScore,stay_score:s.stayScore,cbp_score:s.cbpScore,usda_score:s.usdaScore,tsa_score:s.tsaScore,readiness_score:s.readiness,blockers:s.blockers});if(error)throw error;showToast('Balance guardado en el historial.','success');}
async function completeTrip(){const {error}=await supabase.from('trips').update({status:'completed'}).eq('id',state.selectedTrip.id).eq('user_id',state.user.id);if(error)throw error;await loadTrips();state.selectedTrip=state.trips.find(t=>t.id===state.selectedTrip.id);renderAll();showToast('Viaje marcado como completado.','success');}
async function toggleCatalogActive(id,active){if(!state.isAdmin)return;const {error}=await supabase.from('catalog_items').update({active:!active}).eq('id',id);if(error)throw error;await loadCatalog();await renderAdmin();showToast(`Artículo ${!active?'activado':'desactivado'}.`,'success');}
async function addAdminCatalogItem(e){e.preventDefault();if(!state.isAdmin)return;const payload={canonical_name_es:$('adminItemEs').value.trim(),canonical_name_en:$('adminItemEn').value.trim(),category:$('adminItemCategory').value.trim(),subcategory:$('adminItemSubcategory').value.trim()||null,default_risk:$('adminItemRisk').value,active:true};const {error}=await supabase.from('catalog_items').insert(payload);if(error)throw error;closeDialog('adminCatalogDialog');e.target.reset();$('adminItemCategory').value='food';await loadCatalog();await renderAdmin();showToast('Artículo regulatorio creado.','success');}

async function handleAuthSubmit(e){e.preventDefault();const email=$('emailInput').value.trim(),password=$('passwordInput').value;const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;if(data.session)await initAuthenticated(data.session);}
async function handleSignup(){const email=$('emailInput').value.trim(),password=$('passwordInput').value;if(!email||password.length<8){showToast('Usa un correo válido y una contraseña de al menos 8 caracteres.','error');return;}const redirect=`${window.location.origin}${window.location.pathname}`;const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:redirect}});if(error)throw error;if(data.session)await initAuthenticated(data.session);else showToast('Cuenta creada. Revisa tu correo para confirmar el acceso.','success');}
async function forgotPassword(){const email=$('emailInput').value.trim();if(!email){showToast('Escribe tu correo primero.','error');return;}const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}${window.location.pathname}`});if(error)throw error;showToast('Te enviamos un enlace para restablecer tu contraseña.','success');}
async function signOut(){await supabase.auth.signOut();initSignedOut();}

function bindStaticEvents(){
  $('authForm').addEventListener('submit',e=>handleAuthSubmit(e).catch(handleError));$('signupBtn').addEventListener('click',()=>handleSignup().catch(handleError));$('forgotPasswordBtn').addEventListener('click',()=>forgotPassword().catch(handleError));$('togglePassword').addEventListener('click',()=>{$('passwordInput').type=$('passwordInput').type==='password'?'text':'password';});
  $('brandHomeBtn').addEventListener('click',()=>switchView('dashboard'));$('headerSearchBtn').addEventListener('click',()=>switchView('catalog'));$('headerBellBtn').addEventListener('click',()=>switchView('dashboard'));$('profileButton').addEventListener('click',()=>switchView(state.isAdmin?'admin':'profile'));
  $('bottomNav').querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
  document.querySelectorAll('[data-close-dialog]').forEach(b=>b.addEventListener('click',()=>closeDialog(b.dataset.closeDialog)));
  $('wizardNextBtn').addEventListener('click',nextWizard);$('wizardBackBtn').addEventListener('click',backWizard);$('tripWizardForm').addEventListener('submit',e=>createTrip(e).catch(handleError));$('bagForm').addEventListener('submit',e=>addBag(e).catch(handleError));$('itemForm').addEventListener('submit',e=>addItem(e).catch(handleError));$('documentForm').addEventListener('submit',e=>addDocument(e).catch(handleError));$('adminCatalogForm').addEventListener('submit',e=>addAdminCatalogItem(e).catch(handleError));
}

bindStaticEvents();
const {data:{session}}=await supabase.auth.getSession();if(session)await initAuthenticated(session).catch(handleError);else initSignedOut();
supabase.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT')initSignedOut();else if(session&&!state.session)setTimeout(()=>initAuthenticated(session).catch(handleError),0);});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
