import { createClient } from './supabase-local.js';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './config.js';

const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);
const state={session:null,user:null,profile:null,isAdmin:false,view:'dashboard',trips:[],allItems:[],catalog:[],selectedTrip:null,bags:[],items:[],documents:[],snapshots:[],packingTab:'items',packingFilter:'all',catalogFilter:'all',catalogQuery:'',itemVerification:null,moveItemId:null,adminPanel:'overview',adminCatalog:[],adminRules:[],adminSources:[],adminVerifications:[]};
const GROUPS={regulated:'Alimentos y artículos regulados',clothing:'Ropa y calzado',electronics:'Electrónicos',personal_care:'Cuidado personal',medication:'Medicamentos',documents:'Documentos y papeles',gifts:'Regalos',other:'Otros'};
const GROUP_ICONS={regulated:'food',clothing:'shirt',electronics:'laptop',personal_care:'bottle',medication:'pill',documents:'document',gifts:'gift',other:'box'};
const RISK_LABELS={low:'Bajo',medium:'Medio',high:'Alto',review:'Revisar'};
const DECISION_LABELS={allowed:'Permitido',allowed_declare:'Permitido con declaración',restricted:'Permitido con condiciones',prohibited:'No llevar',review:'Revisión obligatoria'};

function icon(name,cls=''){return `<svg class="icon ${cls}" aria-hidden="true"><use href="#i-${name}"></use></svg>`;}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function fmtDate(v,mode='short'){if(!v)return 'Pendiente';const d=new Date(`${v}T12:00:00`);const opts=mode==='day'?{day:'2-digit'}:mode==='month'?{month:'short'}:mode==='full'?{day:'numeric',month:'long',year:'numeric'}:{day:'numeric',month:'short',year:'numeric'};return d.toLocaleDateString('es-HN',opts).replace('.','');}
function daysBetween(a,b){if(!a||!b)return 0;return Math.max(0,Math.round((Date.parse(`${b}T00:00:00Z`)-Date.parse(`${a}T00:00:00Z`))/86400000));}
function daysUntil(v){if(!v)return null;const t=new Date(`${v}T00:00:00`);const d=new Date();d.setHours(0,0,0,0);return Math.ceil((t-d)/86400000);}
function initials(){const raw=state.profile?.display_name||state.user?.email?.split('@')[0]||'US';return raw.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();}
function userName(){const raw=state.profile?.display_name||state.user?.email?.split('@')[0]||'Viajero';return raw.length>24?'Viajero':raw;}
function showToast(message,type=''){const el=$('toast');if(!el)return;el.textContent=message;el.className=`toast ${type}`;clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>el.classList.add('hidden'),4600);}
function handleError(error){console.error(error);showToast(error?.message||'Ocurrió un error inesperado.','error');}
function openDialog(id){const d=$(id);if(d&&!d.open)d.showModal();}
function closeDialog(id){const d=$(id);if(d?.open)d.close();}
function riskTone(risk){return risk==='low'?'success':risk==='medium'||risk==='review'?'warning':'danger';}
function decisionTone(decision){return decision==='allowed'||decision==='allowed_declare'?'success':decision==='restricted'||decision==='review'?'warning':'danger';}
function itemName(i){return i.catalog_items?.canonical_name_es||i.custom_name||'Artículo';}
function groupLabel(v){return GROUPS[v]||GROUPS.other;}
function groupIcon(v){return GROUP_ICONS[v]||'box';}
function bagLabel(type){return ({personal_item:'Artículo personal',carry_on:'Carry-on',checked:'Maleta facturada'})[type]||'Equipaje';}
function tripRoute(t){return `SAP → ${t.entry_airport||'USA'}`;}
function purposeLabel(v){return ({tourism:'Turismo',family:'Visita familiar',business:'Negocios',study:'Estudio',other:'Otro'})[v]||'Viaje';}
function statusLabel(v){return ({planned:'Próximo',active:'En curso',completed:'Completado',cancelled:'Cancelado'})[v]||v;}
function nextTrip(){const today=new Date().toISOString().slice(0,10);return [...state.trips].filter(t=>t.status!=='cancelled'&&t.departure_date>=today).sort((a,b)=>a.departure_date.localeCompare(b.departure_date))[0]||state.trips.find(t=>t.status==='active')||state.trips[0]||null;}

async function ensureProfile(){const r=await supabase.from('profiles').select('*').eq('user_id',state.user.id).maybeSingle();if(r.error)throw r.error;if(r.data){state.profile=r.data;return;}const display=state.user.email?.split('@')[0]||'Viajero';const ins=await supabase.from('profiles').insert({user_id:state.user.id,display_name:display}).select('*').single();if(ins.error)throw ins.error;state.profile=ins.data;}
async function detectAdmin(){const r=await supabase.from('admin_users').select('user_id').eq('user_id',state.user.id).maybeSingle();if(r.error)throw r.error;state.isAdmin=!!r.data;}
async function loadCatalog(){const r=await supabase.from('catalog_items').select('*').eq('active',true).order('canonical_name_es');if(r.error)throw r.error;state.catalog=r.data||[];}
async function loadTrips(){const r=await supabase.from('trips').select('*').eq('user_id',state.user.id).order('departure_date',{ascending:false});if(r.error)throw r.error;state.trips=r.data||[];}
async function loadAllItems(){const r=await supabase.from('trip_items').select('id,trip_id,item_group,packed,regulatory_required,computed_decision,computed_risk,declared').eq('user_id',state.user.id);if(r.error)throw r.error;state.allItems=r.data||[];}
async function loadTripData(id){if(!id){state.selectedTrip=null;state.bags=[];state.items=[];state.documents=[];state.snapshots=[];return;}state.selectedTrip=state.trips.find(t=>t.id===id)||null;if(!state.selectedTrip)return;const [bags,items,docs,snaps]=await Promise.all([
  supabase.from('trip_bags').select('*').eq('trip_id',id).eq('user_id',state.user.id).order('created_at'),
  supabase.from('trip_items').select('*, catalog_items(canonical_name_es,canonical_name_en,category,subcategory), regulatory_rules(explanation,traveler_action,declaration_required,regulatory_sources(agency,title,url))').eq('trip_id',id).eq('user_id',state.user.id).order('created_at'),
  supabase.from('trip_documents').select('*').eq('trip_id',id).eq('user_id',state.user.id).order('created_at',{ascending:false}),
  supabase.from('compliance_snapshots').select('*').eq('trip_id',id).eq('user_id',state.user.id).order('created_at',{ascending:false})
]);for(const r of [bags,items,docs,snaps])if(r.error)throw r.error;state.bags=bags.data||[];state.items=items.data||[];state.documents=docs.data||[];state.snapshots=snaps.data||[];await loadAllItems();}
async function loadBase(){await Promise.all([ensureProfile(),detectAdmin(),loadCatalog(),loadTrips(),loadAllItems()]);const chosen=state.selectedTrip?.id||nextTrip()?.id||null;if(chosen)await loadTripData(chosen);}

function tripItems(id){return state.allItems.filter(i=>i.trip_id===id);}
function tripReadiness(t,items=tripItems(t.id),docs=state.selectedTrip?.id===t.id?state.documents:[]){const info=[t.departure_date,t.return_date,t.airline,t.entry_airport,t.purpose].filter(Boolean).length/5*100;const pack=items.length?items.filter(i=>i.packed).length/items.length*100:0;const blockers=items.filter(i=>['prohibited','review'].includes(i.computed_decision)).length;const declarations=items.filter(i=>i.computed_decision==='allowed_declare');const declaredOk=declarations.length?declarations.filter(i=>i.declared).length/declarations.length*100:100;const reg=blockers?0:declaredOk;const docScore=docs.length?Math.min(100,docs.length/3*100):0;return Math.round((info+pack+reg+docScore)/4);}
function currentScores(){const t=state.selectedTrip;if(!t)return {readiness:0,packing:0,docs:0,regulatory:0,blockers:[]};const total=state.items.length,packed=state.items.filter(i=>i.packed).length;const packing=total?Math.round(packed/total*100):0;const docs=Math.min(100,Math.round(state.documents.length/3*100));const blockers=state.items.filter(i=>['prohibited','review'].includes(i.computed_decision));const declare=state.items.filter(i=>i.computed_decision==='allowed_declare');const declarationOk=declare.length?declare.every(i=>i.declared):true;const regulatory=blockers.length?0:declarationOk?100:72;const info=[t.departure_date,t.return_date,t.airline,t.entry_airport,t.purpose].filter(Boolean).length/5*100;const readiness=Math.round((packing+docs+regulatory+info)/4);return {readiness,packing,docs,regulatory,blockers,packed,total,declarationOk};}

function setView(view){if(view==='admin'&&!state.isAdmin)view='profile';state.view=view;document.querySelectorAll('[data-view-panel]').forEach(el=>el.classList.toggle('hidden',el.dataset.viewPanel!==view));document.querySelectorAll('[data-nav]').forEach(el=>el.classList.toggle('active',el.dataset.nav===view));renderCurrentView();window.scrollTo({top:0,behavior:'smooth'});}
function renderCurrentView(){if(state.view==='dashboard')renderDashboard();if(state.view==='trips')renderTrips();if(state.view==='packing')renderPacking();if(state.view==='documents')renderDocuments();if(state.view==='catalog')renderCatalog();if(state.view==='profile')renderProfile();if(state.view==='admin')renderAdmin().catch(handleError);}
function bindNav(root=document){root.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.nav)));root.querySelectorAll('[data-action="new-trip"]').forEach(b=>b.addEventListener('click',openTripWizard));root.querySelectorAll('[data-action="new-item"]').forEach(b=>b.addEventListener('click',openItemWizard));root.querySelectorAll('[data-action="new-bag"]').forEach(b=>b.addEventListener('click',()=>{if(!state.selectedTrip)return showToast('Selecciona un viaje primero.','error');$('bagForm').reset();openDialog('bagDialog');}));root.querySelectorAll('[data-action="new-document"]').forEach(b=>b.addEventListener('click',()=>{if(!state.selectedTrip)return showToast('Selecciona un viaje primero.','error');$('documentForm').reset();openDialog('documentDialog');}));}

function renderDashboard(){const host=$('dashboardView');const t=state.selectedTrip||nextTrip();const items=t?tripItems(t.id):[];const score=t?tripReadiness(t,items,state.selectedTrip?.id===t.id?state.documents:[]):0;const d=t?daysUntil(t.departure_date):null;const alerts=items.filter(i=>['prohibited','review','restricted'].includes(i.computed_decision)||i.computed_decision==='allowed_declare'&&!i.declared);const boarding=t?`<article class="boarding-card"><div class="boarding-top"><span class="boarding-kicker">Próximo viaje</span><span class="pill ${d!==null&&d<=7?'warning':'info'}">${d===0?'Hoy':d!==null&&d>0?`En ${d} días`:statusLabel(t.status)}</span></div><div class="boarding-route"><strong>SAP</strong><span class="route-dash">${icon('plane')}</span><strong>${esc(t.entry_airport||'USA')}</strong></div><div class="boarding-meta"><span>Salida<b>${fmtDate(t.departure_date)}</b></span><span>Regreso<b>${fmtDate(t.return_date)}</b></span><span>Aerolínea<b>${esc(t.airline||'Pendiente')}</b></span></div><button class="button secondary compact" style="position:absolute;left:30px;bottom:28px;z-index:2" data-nav="packing">Preparar equipaje ${icon('arrow','sm')}</button></article>`:`<article class="boarding-card"><div class="boarding-empty">${icon('plane','lg')}<span class="boarding-kicker">Tu próximo viaje</span><h2>Empieza con un expediente.</h2><p>Registra el viaje y EntrySafe organizará lo que llevarás, tus maletas, documentos y verificaciones.</p><button class="button secondary" data-action="new-trip">Crear primer viaje</button></div></article>`;
  const scores=state.selectedTrip?currentScores():{packing:0,docs:0,regulatory:0};host.innerHTML=`<div class="welcome"><p class="eyebrow">${state.isAdmin?'Cuenta administradora':'Tu espacio privado'}</p><h1>Hola, ${esc(userName())}.</h1><p>${t?'Todo lo importante de tu próximo viaje, en un solo lugar.':'Crea tu primer viaje para comenzar a preparar todo lo que llevarás.'}</p></div><div class="trip-focus">${boarding}<article class="readiness-card surface"><div><p class="eyebrow">Estado del viaje</p><h3>${t?'Preparación general':'Sin viaje activo'}</h3><p>${t?alerts.length?'Hay puntos que revisar antes de marcar el viaje como listo.':'Sigue tu checklist hasta completar el viaje.':'Crea un viaje para activar tu checklist.'}</p></div><div><div class="readiness-number">${score}<small>/100</small></div><div class="progress"><i style="width:${score}%"></i></div></div></article></div><div class="quick-grid"><article class="quick-card"><span class="icon-wrap">${icon('suitcase')}</span><strong>${state.trips.length}</strong><span>Viajes registrados</span></article><article class="quick-card"><span class="icon-wrap">${icon('list')}</span><strong>${items.length}</strong><span>Artículos planeados</span></article><article class="quick-card"><span class="icon-wrap">${icon('check')}</span><strong>${items.filter(i=>i.packed).length}</strong><span>Artículos empacados</span></article><article class="quick-card"><span class="icon-wrap">${icon('alert')}</span><strong>${alerts.length}</strong><span>Puntos por revisar</span></article></div><div class="dashboard-columns"><article class="panel"><div class="panel-head"><h2>Tu checklist</h2><button data-nav="packing">Abrir preparación</button></div><div class="task-list">${dashboardTask('Datos del viaje',t?80:0,t?'Vuelo, fechas y destino registrados.':'Crea un viaje para comenzar.','calendar')}${dashboardTask('Lo que llevaré',scores.packing,items.length?`${items.filter(i=>i.packed).length} de ${items.length} artículos empacados.`:'Agrega lo que planeas llevar.','list')}${dashboardTask('Documentos',scores.docs,state.documents.length?`${state.documents.length} documento(s) registrados.`:'Agrega pasaporte, visa y reservas.','document')}${dashboardTask('Regulación',scores.regulatory,alerts.length?`${alerts.length} punto(s) requieren atención.`:'Sin bloqueos regulatorios detectados.','shield')}</div></article><article class="panel"><div class="panel-head"><h2>Fuentes oficiales</h2><button data-nav="catalog">Consultar</button></div><div class="authority-list">${authority('USDA / APHIS','Productos agrícolas')}${authority('CBP','Declaración y entrada')}${authority('TSA','Equipaje y seguridad')}${authority('FDA','Importación personal')}</div></article></div>`;bindNav(host);}
function dashboardTask(title,score,copy,ico){const tone=score>=90?'done':score>0?'warn':'';return `<div class="task"><span class="task-state ${tone}">${icon(score>=90?'check':ico,'sm')}</span><div class="task-copy"><b>${esc(title)}</b><span>${esc(copy)}</span></div><span class="pill ${score>=90?'success':score>0?'warning':''}">${Math.round(score)}%</span></div>`;}
function authority(name,desc){return `<div class="authority-row"><div><b>${esc(name)}</b><small class="muted">${esc(desc)}</small></div><span>Oficial</span></div>`;}

function renderTrips(){const host=$('tripsView');host.innerHTML=`<div class="page-head"><div><p class="eyebrow">Historial personal</p><h1 class="page-title">Mis viajes</h1><p>Un expediente independiente para cada entrada a Estados Unidos.</p></div><div class="page-actions"><button class="button primary" data-action="new-trip">${icon('plus','sm')} Nuevo viaje</button></div></div><div class="trip-grid">${state.trips.length?state.trips.map(t=>{const items=tripItems(t.id);const score=tripReadiness(t,items,state.selectedTrip?.id===t.id?state.documents:[]);return `<article class="trip-card" data-open-trip="${t.id}"><div class="trip-card-top"><div class="trip-date"><strong>${fmtDate(t.departure_date,'day')}</strong><span>${fmtDate(t.departure_date,'month')}</span></div><span class="pill ${t.status==='completed'?'success':'info'}">${esc(statusLabel(t.status))}</span></div><div class="trip-route">${esc(tripRoute(t))}</div><p>${esc(t.airline||'Aerolínea pendiente')} · ${esc(purposeLabel(t.purpose))}</p><div class="trip-card-foot"><span class="trip-score"><b>${score}</b>/100 preparación</span><button class="button secondary compact">Abrir ${icon('arrow','sm')}</button></div></article>`}).join(''):`<div class="empty" style="grid-column:1/-1"><span class="empty-icon">${icon('plane','lg')}</span><h3>Aún no hay viajes.</h3><p>Crea tu primer expediente y luego construye tu lista completa de equipaje.</p><button class="button primary" data-action="new-trip">Crear viaje</button></div>`}</div>`;host.querySelectorAll('[data-open-trip]').forEach(card=>card.addEventListener('click',async()=>{await loadTripData(card.dataset.openTrip);state.packingTab='items';setView('packing');}));bindNav(host);}

function renderPacking(){const host=$('packingView');if(!state.selectedTrip){host.innerHTML=`<div class="page-head"><div><p class="eyebrow">Preparación</p><h1 class="page-title">Mi equipaje</h1></div></div><div class="empty"><span class="empty-icon">${icon('suitcase','lg')}</span><h3>Selecciona un viaje.</h3><p>Abre un viaje para preparar lo que llevarás, tus maletas y declaración.</p><button class="button primary" data-nav="trips">Ver viajes</button></div>`;bindNav(host);return;}const t=state.selectedTrip;host.innerHTML=`<div class="packing-header"><div><p class="eyebrow">Preparación del viaje</p><h1 class="page-title">${esc(tripRoute(t))}</h1><div class="trip-context">${icon('calendar','sm')} <span>${fmtDate(t.departure_date,'full')} — ${fmtDate(t.return_date,'full')}</span><span>·</span><strong>${esc(t.airline||'Aerolínea pendiente')}</strong></div></div><div class="page-actions"><button class="button secondary" data-action="new-bag">${icon('suitcase','sm')} Nueva maleta</button><button class="button primary" data-action="new-item">${icon('plus','sm')} Agregar artículo</button></div></div><div class="workspace-tabs"><button class="workspace-tab ${state.packingTab==='items'?'active':''}" data-pack-tab="items">Lo que llevaré</button><button class="workspace-tab ${state.packingTab==='bags'?'active':''}" data-pack-tab="bags">Maletas</button><button class="workspace-tab ${state.packingTab==='declaration'?'active':''}" data-pack-tab="declaration">Declaración</button><button class="workspace-tab ${state.packingTab==='closeout'?'active':''}" data-pack-tab="closeout">Cierre del viaje</button></div><div id="packingContent"></div>`;host.querySelectorAll('[data-pack-tab]').forEach(b=>b.addEventListener('click',()=>{state.packingTab=b.dataset.packTab;renderPackingContent();}));bindNav(host);renderPackingContent();}
function renderPackingContent(){const host=$('packingContent');if(!host)return;if(state.packingTab==='items')renderPackingItems(host);if(state.packingTab==='bags')renderBags(host);if(state.packingTab==='declaration')renderDeclaration(host);if(state.packingTab==='closeout')renderCloseout(host);}
function renderPackingItems(host){let items=[...state.items];if(state.packingFilter!=='all')items=items.filter(i=>i.item_group===state.packingFilter);const packed=state.items.filter(i=>i.packed).length;host.innerHTML=`<div class="packing-summary"><div class="summary-mini"><strong>${state.items.length}</strong><span>artículos planeados</span></div><div class="summary-mini"><strong>${packed}</strong><span>empacados</span></div><div class="summary-mini"><strong>${state.items.filter(i=>i.regulatory_required).length}</strong><span>con control regulatorio</span></div></div><div class="packing-toolbar"><div class="packing-search input-with-icon">${icon('search')}<input id="packingSearch" aria-label="Buscar en mi equipaje" placeholder="Buscar en lo que llevaré…"></div><button class="button primary" data-action="new-item">${icon('plus','sm')} Agregar artículo</button></div><div class="category-chips"><button class="chip ${state.packingFilter==='all'?'active':''}" data-pack-filter="all">Todo</button>${Object.entries(GROUPS).map(([k,v])=>`<button class="chip ${state.packingFilter===k?'active':''}" data-pack-filter="${k}">${esc(v)}</button>`).join('')}</div><div id="packingRows" class="packing-list">${packingRows(items)}</div>`;host.querySelectorAll('[data-pack-filter]').forEach(b=>b.addEventListener('click',()=>{state.packingFilter=b.dataset.packFilter;renderPackingContent();}));$('packingSearch')?.addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();const filtered=items.filter(i=>itemName(i).toLowerCase().includes(q));$('packingRows').innerHTML=packingRows(filtered);bindPackingRows();});bindNav(host);bindPackingRows();}
function packingRows(items){if(!items.length)return `<div class="empty"><span class="empty-icon">${icon('list','lg')}</span><h3>Tu lista está vacía.</h3><p>Agrega absolutamente todo lo que planeas llevar. EntrySafe separará automáticamente lo normal de lo que necesita verificación oficial.</p><button class="button primary" data-action="new-item">Agregar primer artículo</button></div>`;return items.map(i=>{const bag=state.bags.find(b=>b.id===i.bag_id);const status=i.regulatory_required?`<span class="pill ${decisionTone(i.computed_decision)}"><span class="dot"></span>${esc(DECISION_LABELS[i.computed_decision]||'Verificado')}</span>`:`<span class="pill info">Checklist personal</span>`;return `<article class="packing-item"><button class="pack-check ${i.packed?'checked':''}" data-pack-id="${i.id}" aria-label="${i.packed?'Marcar como no empacado':'Marcar como empacado'}">${i.packed?icon('check','sm'):''}</button><div class="item-main"><div class="item-heading"><span class="group-icon">${icon(groupIcon(i.item_group))}</span><div><div class="item-title-row"><b>${esc(itemName(i))}</b>${status}</div><div class="item-sub"><span>${esc(groupLabel(i.item_group))}</span><span>·</span><span>${bag?esc(bag.label):'Sin maleta'}</span><span>·</span><span>${Number(i.quantity)||1} ${esc(i.unit||'unidad')}</span>${i.declared?'<span>· Declarado</span>':''}</div></div></div></div><div class="item-actions"><button class="icon-button" data-move-id="${i.id}" title="Cambiar maleta">${icon('suitcase','sm')}</button><button class="icon-button" data-delete-id="${i.id}" title="Eliminar">${icon('trash','sm')}</button></div></article>`}).join('');}
function bindPackingRows(){document.querySelectorAll('[data-pack-id]').forEach(b=>b.addEventListener('click',()=>togglePacked(b.dataset.packId).catch(handleError)));document.querySelectorAll('[data-delete-id]').forEach(b=>b.addEventListener('click',()=>deleteItem(b.dataset.deleteId).catch(handleError)));document.querySelectorAll('[data-move-id]').forEach(b=>b.addEventListener('click',()=>openMoveDialog(b.dataset.moveId)));document.querySelectorAll('#packingRows [data-action="new-item"]').forEach(b=>b.addEventListener('click',openItemWizard));}
function renderBags(host){host.innerHTML=`<div class="page-head" style="margin-bottom:16px"><div><h2 class="section-title">Tus maletas</h2><p>Asigna cada artículo al equipaje donde realmente viajará.</p></div><button class="button primary" data-action="new-bag">${icon('plus','sm')} Nueva maleta</button></div><div class="bag-grid">${state.bags.length?state.bags.map(b=>{const list=state.items.filter(i=>i.bag_id===b.id);const packed=list.filter(i=>i.packed).length;const ico=b.bag_type==='personal_item'?'backpack':b.bag_type==='carry_on'?'carryon':'suitcase';return `<article class="bag-card"><div class="bag-card-head"><span class="bag-symbol">${icon(ico,'lg')}</span><span class="pill info">${esc(bagLabel(b.bag_type))}</span></div><h3>${esc(b.label)}</h3><p>${b.weight_kg?`${esc(b.weight_kg)} kg registrados`:'Peso opcional'}</p><div class="bag-count">${list.length}<span> artículos · ${packed} empacados</span></div><div class="progress green" style="margin-top:12px"><i style="width:${list.length?Math.round(packed/list.length*100):0}%"></i></div></article>`}).join(''):`<div class="empty" style="grid-column:1/-1"><span class="empty-icon">${icon('suitcase','lg')}</span><h3>Aún no registraste maletas.</h3><p>Crea artículo personal, carry-on o equipaje facturado y luego asigna cada cosa a su lugar.</p><button class="button primary" data-action="new-bag">Crear maleta</button></div>`}</div>`;bindNav(host);}
function renderDeclaration(host){const relevant=state.items.filter(i=>i.regulatory_required&&(i.computed_decision==='allowed_declare'||i.computed_decision==='restricted'||i.declared));host.innerHTML=`<article class="declaration-card surface"><div class="declaration-intro"><div><p class="eyebrow">Resumen para CBP</p><h2>Productos que debes tener presentes al declarar</h2><p>EntrySafe toma esta lista directamente de “Lo que llevaré”. No sustituye la inspección: declara todos los productos agrícolas o de origen animal que correspondan.</p></div><span class="pill info">${relevant.length} producto(s)</span></div><div class="declare-list">${relevant.length?relevant.map(i=>`<div class="declare-row"><div><b>${esc(i.catalog_items?.canonical_name_en||itemName(i))}</b><span>${esc(itemName(i))} · ${esc(DECISION_LABELS[i.computed_decision]||'Revisado')}</span></div><button class="button ${i.declared?'secondary':'primary'} compact" data-declare-id="${i.id}">${i.declared?`${icon('check','sm')} Declarado`:'Marcar declarado'}</button></div>`).join(''):`<div class="empty"><span class="empty-icon">${icon('shield','lg')}</span><h3>No hay productos pendientes de declaración.</h3><p>Cuando agregues artículos que deban declararse, aparecerán aquí automáticamente.</p></div>`}</div></article>`;host.querySelectorAll('[data-declare-id]').forEach(b=>b.addEventListener('click',()=>toggleDeclared(b.dataset.declareId).catch(handleError)));}
function renderCloseout(host){const s=currentScores();const severe=s.blockers.length;const unPacked=s.total-s.packed;const declarationPending=!s.declarationOk;const ready=s.total>0&&!severe&&!unPacked&&!declarationPending&&s.docs>=67;host.innerHTML=`<div class="closeout-grid"><article class="closeout-card surface"><p class="eyebrow">Preparación</p><h3>Checklist de equipaje</h3><div class="closeout-score">${s.packing}<small>%</small></div><div class="progress ${s.packing===100?'green':''}"><i style="width:${s.packing}%"></i></div><p class="subcopy">${s.packed} de ${s.total} artículos marcados como empacados.</p></article><article class="closeout-card surface"><p class="eyebrow">Documentación</p><h3>Documentos del viaje</h3><div class="closeout-score">${s.docs}<small>%</small></div><div class="progress"><i style="width:${s.docs}%"></i></div><p class="subcopy">${state.documents.length} documento(s) registrados en tu espacio privado.</p></article><article class="closeout-card surface"><p class="eyebrow">Regulación</p><h3>Control previo</h3><div class="closeout-score">${s.regulatory}<small>%</small></div><p class="subcopy">${severe?`${severe} artículo(s) bloquean el cierre.`:declarationPending?'Aún hay declaraciones pendientes.':'Sin bloqueos regulatorios pendientes.'}</p></article><article class="closeout-card surface"><p class="eyebrow">Resultado</p><h3>Preparación general</h3><div class="closeout-score">${s.readiness}<small>/100</small></div><button class="button secondary compact" id="snapshotBtn">Guardar balance</button></article><div class="ready-banner ${ready?'':'blocked'}"><h3>${ready?'Viaje listo para tu revisión final.':'Todavía no marques este viaje como listo.'}</h3><p>${ready?'Tu checklist está completo dentro de la cobertura actual de EntrySafe. La decisión final de admisión y de productos siempre corresponde a las autoridades estadounidenses.':[unPacked?`${unPacked} artículo(s) aún no están empacados.`:'',severe?`${severe} artículo(s) requieren revisión regulatoria.`:'',declarationPending?'Hay productos pendientes de marcar como declarados.':'',s.docs<67?'Completa tus documentos principales.':''].filter(Boolean).join(' ')}</p>${ready?'<button class="button primary compact" id="completeTripBtn" style="margin-top:14px">Marcar viaje completado</button>':''}</div></div>`;$('snapshotBtn')?.addEventListener('click',()=>saveSnapshot().catch(handleError));$('completeTripBtn')?.addEventListener('click',()=>completeTrip().catch(handleError));}

function renderDocuments(){const host=$('documentsView');host.innerHTML=`<div class="page-head"><div><p class="eyebrow">Bóveda privada</p><h1 class="page-title">Documentos</h1><p>Pasaporte, visa, boleto, hospedaje, seguro e I-94 vinculados al viaje actual.</p></div><div class="page-actions"><button class="button primary" data-action="new-document">${icon('plus','sm')} Agregar documento</button></div></div>${state.selectedTrip?`<div class="document-grid">${state.documents.length?state.documents.map(d=>`<article class="document-card"><span class="group-icon">${icon(docIcon(d.document_type),'lg')}</span><h3>${esc(docLabel(d.document_type))}</h3><p>${esc(d.masked_identifier||'Identificador protegido')}</p><div class="document-card-foot"><span class="pill ${d.expires_on&&daysUntil(d.expires_on)<90?'warning':'success'}">${d.expires_on?`Vence ${fmtDate(d.expires_on)}`:'Guardado'}</span><button class="icon-button" data-delete-doc="${d.id}">${icon('trash','sm')}</button></div></article>`).join(''):`<div class="empty" style="grid-column:1/-1"><span class="empty-icon">${icon('document','lg')}</span><h3>Tu bóveda está vacía.</h3><p>Agrega metadatos y archivos privados del viaje. Los archivos permanecen en almacenamiento privado.</p><button class="button primary" data-action="new-document">Agregar documento</button></div>`}</div>`:`<div class="empty"><span class="empty-icon">${icon('document','lg')}</span><h3>Selecciona un viaje.</h3><p>Los documentos se organizan por expediente.</p><button class="button primary" data-nav="trips">Ver viajes</button></div>`}`;host.querySelectorAll('[data-delete-doc]').forEach(b=>b.addEventListener('click',()=>deleteDocument(b.dataset.deleteDoc).catch(handleError)));bindNav(host);}
function docIcon(v){return v==='passport'?'passport':v==='visa'?'shield':v==='ticket'?'plane':'document';}
function docLabel(v){return ({passport:'Pasaporte',visa:'Visa',i94:'I-94',ticket:'Boleto aéreo',hotel:'Hospedaje',insurance:'Seguro de viaje',other:'Otro documento'})[v]||'Documento';}

function catalogCategoryLabel(item){const c=(item.category||'').toLowerCase(),s=(item.subcategory||'').toLowerCase();if(c==='food')return 'Alimento';if(c==='plant')return 'Planta / agricultura';if(s.includes('poultry'))return 'Producto aviar';if(s.includes('dairy'))return 'Lácteo';return 'Artículo regulado';}
function catalogIcon(item){const text=`${item.category||''} ${item.subcategory||''} ${item.canonical_name_es||''}`.toLowerCase();if(text.includes('coffee')||text.includes('café'))return 'coffee';if(text.includes('pork')||text.includes('cerdo')||text.includes('meat'))return 'food';if(text.includes('dairy')||text.includes('ques')||text.includes('leche'))return 'bottle';if(text.includes('poultry')||text.includes('pollo')||text.includes('gallina'))return 'food';if(text.includes('seed')||text.includes('plant')||text.includes('fruit')||text.includes('veget')||text.includes('soil')||text.includes('flor'))return 'leaf';if(text.includes('fish')||text.includes('seafood')||text.includes('pesc'))return 'food';return 'box';}
function catalogGuidance(item){if(item.default_risk==='high')return 'Requiere una verificación estricta antes de llevarlo.';if(item.default_risk==='review')return 'Debe revisarse con una regla oficial específica.';if(item.default_risk==='medium')return 'Puede depender de preparación, origen o empaque.';return 'Suele tener menor complejidad, pero debe declararse cuando corresponda.';}
function renderCatalog(){const host=$('catalogView');let rows=state.catalog;const q=state.catalogQuery.trim().toLowerCase();if(q)rows=rows.filter(i=>[i.canonical_name_es,i.canonical_name_en,...(i.aliases||[])].filter(Boolean).some(v=>String(v).toLowerCase().includes(q)));if(state.catalogFilter!=='all')rows=rows.filter(i=>i.category===state.catalogFilter);const cats=[...new Set(state.catalog.map(i=>i.category).filter(Boolean))];host.innerHTML=`<section class="catalog-hero"><p class="eyebrow">Consulta regulatoria</p><h1>¿Qué quieres llevar a Estados Unidos?</h1><p>Consulta antes de empacar. Para agregar un producto a un viaje, usa “Lo que llevaré”: EntrySafe verificará las condiciones oficiales antes de guardarlo cuando corresponda.</p><div class="catalog-search input-with-icon">${icon('search')}<input id="catalogQuery" value="${esc(state.catalogQuery)}" placeholder="Buscar queso, café, pollo, semillas…"></div></section><div class="category-chips"><button class="chip ${state.catalogFilter==='all'?'active':''}" data-cat="all">Todos</button>${cats.map(c=>`<button class="chip ${state.catalogFilter===c?'active':''}" data-cat="${esc(c)}">${c==='food'?'Alimentos':c==='plant'?'Plantas y agricultura':'Otros'}</button>`).join('')}</div><div class="catalog-grid">${rows.slice(0,120).map(i=>`<article class="catalog-card"><span class="group-icon">${icon(catalogIcon(i),'lg')}</span><div><h3>${esc(i.canonical_name_es)}</h3><p>${esc(catalogGuidance(i))}</p><div class="catalog-meta"><span class="pill ${riskTone(i.default_risk)}"><span class="dot"></span>${i.default_risk==='high'?'Control alto':i.default_risk==='review'?'Consultar':i.default_risk==='medium'?'Depende de condiciones':'Menor complejidad'}</span><span class="pill">${esc(catalogCategoryLabel(i))}</span></div></div></article>`).join('')||`<div class="empty" style="grid-column:1/-1"><span class="empty-icon">${icon('search','lg')}</span><h3>Sin coincidencias.</h3><p>Prueba con otro nombre o agrégalo desde “Lo que llevaré” para que el verificador intente clasificarlo.</p></div>`}</div>`;$('catalogQuery')?.addEventListener('input',e=>{state.catalogQuery=e.target.value;renderCatalog();});host.querySelectorAll('[data-cat]').forEach(b=>b.addEventListener('click',()=>{state.catalogFilter=b.dataset.cat;renderCatalog();}));}

async function loadAdmin(){const [c,r,s,v]=await Promise.all([supabase.from('catalog_items').select('*').order('canonical_name_es'),supabase.from('regulatory_rules').select('id,decision,risk_level,rule_version,active,last_verified_at').order('last_verified_at',{ascending:false}),supabase.from('regulatory_sources').select('*').order('last_verified_at',{ascending:false}),supabase.from('product_verifications').select('id,product_name,decision,risk_level,source_mode,verified_at,can_save').order('verified_at',{ascending:false})]);for(const x of [c,r,s,v])if(x.error)throw x.error;state.adminCatalog=c.data||[];state.adminRules=r.data||[];state.adminSources=s.data||[];state.adminVerifications=v.data||[];}
async function renderAdmin(){const host=$('adminView');if(!state.isAdmin){host.innerHTML='<div class="empty"><h3>Acceso restringido.</h3></div>';return;}await loadAdmin();host.innerHTML=`<div class="page-head"><div><p class="eyebrow">Regulatory Control Center</p><h1 class="page-title">Administración</h1><p>Reglas, productos, fuentes oficiales y auditoría de verificaciones.</p></div><span class="pill info">Administrador</span></div><div class="admin-kpis"><article class="admin-kpi surface"><strong>${state.adminRules.filter(r=>r.active).length}</strong><span>reglas activas</span></article><article class="admin-kpi surface"><strong>${state.adminCatalog.filter(c=>c.active).length}</strong><span>productos activos</span></article><article class="admin-kpi surface"><strong>${state.adminSources.length}</strong><span>fuentes oficiales</span></article><article class="admin-kpi surface"><strong>${state.adminVerifications.length}</strong><span>verificaciones registradas</span></article></div><div class="admin-shell"><aside class="admin-menu surface"><button class="${state.adminPanel==='overview'?'active':''}" data-admin="overview">Resumen</button><button class="${state.adminPanel==='catalog'?'active':''}" data-admin="catalog">Productos</button><button class="${state.adminPanel==='rules'?'active':''}" data-admin="rules">Reglas</button><button class="${state.adminPanel==='sources'?'active':''}" data-admin="sources">Fuentes oficiales</button><button class="${state.adminPanel==='audit'?'active':''}" data-admin="audit">Auditoría</button></aside><div id="adminContent" class="admin-content"></div></div>`;host.querySelectorAll('[data-admin]').forEach(b=>b.addEventListener('click',()=>{state.adminPanel=b.dataset.admin;renderAdminContent();host.querySelectorAll('[data-admin]').forEach(x=>x.classList.toggle('active',x.dataset.admin===state.adminPanel));}));renderAdminContent();}
function renderAdminContent(){const host=$('adminContent');if(!host)return;if(state.adminPanel==='overview'){const blocked=state.adminVerifications.filter(v=>!v.can_save).length;host.innerHTML=`<article class="panel"><div class="panel-head"><h2>Estado regulatorio</h2></div><div class="task-list">${dashboardTask('Reglas activas',100,`${state.adminRules.filter(r=>r.active).length} reglas disponibles.`,'shield')}${dashboardTask('Fuentes oficiales',100,`${state.adminSources.length} fuentes registradas.`,'globe')}${dashboardTask('Verificaciones bloqueadas',blocked?70:100,blocked?`${blocked} consultas no autorizaron guardado.`:'Sin bloqueos en la muestra actual.','alert')}</div></article>`;return;}if(state.adminPanel==='catalog'){host.innerHTML=`<div class="admin-table">${state.adminCatalog.slice(0,80).map(i=>`<div class="admin-row"><div><b>${esc(i.canonical_name_es)}</b><span>${esc(catalogCategoryLabel(i))} · ${esc(RISK_LABELS[i.default_risk]||i.default_risk)}</span></div><span class="pill ${i.active?'success':''}">${i.active?'Activo':'Inactivo'}</span></div>`).join('')}</div>`;return;}if(state.adminPanel==='rules'){host.innerHTML=`<div class="admin-table">${state.adminRules.slice(0,80).map(r=>`<div class="admin-row"><div><b>${esc(r.rule_version)}</b><span>${esc(DECISION_LABELS[r.decision]||r.decision)} · riesgo ${esc(RISK_LABELS[r.risk_level]||r.risk_level)}</span></div><span class="pill ${r.active?'success':''}">${r.active?'Activa':'Inactiva'}</span></div>`).join('')}</div>`;return;}if(state.adminPanel==='sources'){host.innerHTML=`<div class="admin-table">${state.adminSources.map(s=>`<div class="admin-row"><div><b>${esc(s.agency)} · ${esc(s.title)}</b><span>Verificada ${new Date(s.last_verified_at).toLocaleDateString('es-HN')}</span></div><a class="button secondary compact" href="${esc(s.url)}" target="_blank" rel="noopener">Abrir ${icon('external','sm')}</a></div>`).join('')}</div>`;return;}host.innerHTML=`<div class="admin-table">${state.adminVerifications.slice(0,100).map(v=>`<div class="admin-row"><div><b>${esc(v.product_name)}</b><span>${new Date(v.verified_at).toLocaleString('es-HN')} · ${esc(v.source_mode)}</span></div><span class="pill ${decisionTone(v.decision)}">${esc(DECISION_LABELS[v.decision]||v.decision)}</span></div>`).join('')}</div>`;}

function renderProfile(){const host=$('profileView');host.innerHTML=`<div class="page-head"><div><p class="eyebrow">Cuenta privada</p><h1 class="page-title">Perfil y seguridad</h1></div></div><div class="profile-layout"><article class="profile-card surface"><div class="profile-avatar">${esc(initials())}</div><h2>${esc(userName())}</h2><p>${esc(state.user?.email||'')}</p>${state.isAdmin?'<span class="pill info" style="margin-top:14px">Administrador</span>':''}<div class="settings-list"><div class="setting-row"><b>País de origen</b><span>Honduras</span></div><div class="setting-row"><b>Idioma</b><span>Español</span></div><div class="setting-row"><b>Protección de datos</b><span>RLS activo</span></div></div></article><article class="profile-card surface"><p class="eyebrow">Sesión</p><h2>Este dispositivo</h2><p>Tu sesión se mantiene de forma privada en este navegador.</p><div class="settings-list"><div class="setting-row"><b>Autenticación</b><span>Supabase Auth</span></div><div class="setting-row"><b>Archivos</b><span>Storage privado</span></div></div><button id="signOutBtn" class="button danger full" style="margin-top:20px">${icon('logout','sm')} Cerrar sesión</button></article></div>`;$('signOutBtn').addEventListener('click',signOut);}

function openTripWizard(){$('tripForm').reset();openDialog('tripDialog');}
async function createTrip(e){e.preventDefault();const dep=$('tripDeparture').value,ret=$('tripReturn').value||null;if(ret&&ret<dep)throw new Error('La fecha de regreso no puede ser anterior a la salida.');const payload={user_id:state.user.id,origin_country:'HN',destination_country:'US',departure_date:dep,return_date:ret,airline:$('tripAirline').value.trim()||null,flight_number:$('tripFlight').value.trim()||null,entry_airport:$('tripAirport').value.trim().toUpperCase()||null,purpose:$('tripPurpose').value,status:'planned',notes:$('tripNotes').value.trim()||null};const r=await supabase.from('trips').insert(payload).select('*').single();if(r.error)throw r.error;closeDialog('tripDialog');await loadTrips();await loadTripData(r.data.id);showToast('Viaje creado. Ahora prepara lo que llevarás.','success');state.packingTab='items';setView('packing');}

function openItemWizard(){if(!state.selectedTrip){showToast('Selecciona o crea un viaje primero.','error');setView('trips');return;}$('itemForm').reset();$('itemQuantity').value='1';$('itemUnit').value='unidad';$('itemGroup').value='regulated';$('itemBag').innerHTML='<option value="">Sin asignar</option>'+state.bags.map(b=>`<option value="${b.id}">${esc(b.label)} · ${esc(bagLabel(b.bag_type))}</option>`).join('');state.itemVerification=null;$('verificationBox').className='verification hidden';$('verificationBox').innerHTML='';updateRegulatoryFields();openDialog('itemDialog');}
function updateRegulatoryFields(){const g=$('itemGroup')?.value;const show=g==='regulated'||g==='medication';$('regulatoryFields')?.classList.toggle('hidden',!show);$('itemSubmit').textContent=show?'Verificar antes de guardar':'Agregar al checklist';}
function looksRegulated(name){const n=name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');const words=['pollo','gallina','cerdo','carne','queso','quesillo','cuajada','leche','mantequilla','huevo','pescado','marisco','cafe','fruta','mango','aguacate','semilla','planta','tierra','suelo','flor','miel','nuez','especia','condimento','tortilla','pan','nacatamal','montuca','tamal','arroz chino','medicamento','medicina','pastilla','receta','power bank','bateria','battery','litio','lithium'];return words.some(w=>n.includes(w));}
function itemNeedsVerification(){const group=$('itemGroup').value,name=$('itemName').value.trim();return group==='regulated'||group==='medication'||looksRegulated(name);}
function itemAttributes(){return {cooked_state:$('itemCooked').value,homemade:$('itemHomemade').checked,commercial_packaging:$('itemCommercial').checked,hermetically_sealed:$('itemSealed').checked,shelf_stable:$('itemShelfStable').checked,contains_meat:$('itemContainsMeat').checked,bag_type:state.bags.find(b=>b.id===$('itemBag').value)?.bag_type||'unassigned'};}
async function verifyItem(acknowledgeRestricted=false){const name=$('itemName').value.trim();if(!name)throw new Error('Escribe el artículo que quieres llevar.');const box=$('verificationBox');box.className='verification';box.innerHTML=`<div class="verification-head"><div><p class="eyebrow">Control previo al guardado</p><h3>Consultando fuentes oficiales…</h3></div>${icon('globe')}</div><p>EntrySafe está contrastando el artículo con las reglas disponibles y fuentes oficiales relevantes.</p>`;const r=await supabase.functions.invoke('verify-travel-product',{body:{productName:name,tripId:state.selectedTrip.id,originCountry:'HN',destinationRegion:'US_CONTINENTAL',attributes:itemAttributes(),acknowledgeRestricted}});if(r.error)throw r.error;if(!r.data?.ok)throw new Error(r.data?.error||'No se pudo completar la verificación.');state.itemVerification=r.data;renderVerification(r.data);return r.data;}
function renderVerification(v){const box=$('verificationBox');const tone=v.decision==='prohibited'||v.decision==='review'?'blocked':v.decision==='restricted'?'warning':'approved';box.className=`verification ${tone}`;const req=(v.requirements||[]).map(x=>`<li>${esc(x)}</li>`).join('');const src=(v.sources||[]).filter(s=>s.url).slice(0,6).map(s=>`<a class="source-link" href="${esc(s.url)}" target="_blank" rel="noopener"><span>${esc(s.agency||'Fuente oficial')}<small>${esc(s.title||'Guía oficial')}</small></span>${icon('external','sm')}</a>`).join('');let action='';if(v.decision==='prohibited')action='<p><b>Este artículo no se puede agregar al checklist como autorizado.</b></p>';else if(v.decision==='review')action='<p><b>La evidencia no es suficiente para autorizarlo. El guardado permanece bloqueado.</b></p>';else if(v.decision==='restricted'&&v.requiresAcknowledgement)action='<button class="button primary full" type="button" id="ackVerification">Confirmar requisitos y volver a verificar</button>';else if(v.canSave)action='<button class="button primary full" type="button" id="saveVerifiedItem">Guardar artículo verificado</button>';box.innerHTML=`<div class="verification-head"><div><p class="eyebrow">Verificación oficial</p><h3>${esc(DECISION_LABELS[v.decision]||'Resultado')}</h3></div><span class="pill ${riskTone(v.riskLevel)}"><span class="dot"></span>${esc(RISK_LABELS[v.riskLevel]||'Revisar')}</span></div><p>${esc(v.explanation||'')}</p>${req?`<b style="font-size:12px">Requisitos</b><ul>${req}</ul>`:''}${src?`<b style="font-size:12px">Fuentes consultadas</b><div class="source-list" style="margin-top:8px">${src}</div>`:''}<div style="margin-top:14px">${action}</div>`;$('ackVerification')?.addEventListener('click',()=>verifyItem(true).catch(handleError));$('saveVerifiedItem')?.addEventListener('click',()=>saveItem(v).catch(handleError),{once:true});}
async function handleItemSubmit(e){e.preventDefault();if(itemNeedsVerification()){await verifyItem(false);return;}await saveItem(null);}
async function saveItem(verification){const name=$('itemName').value.trim();if(!name)throw new Error('Escribe un nombre.');const requires=!!verification||itemNeedsVerification();if(requires&&!verification?.canSave)throw new Error('Este artículo todavía no está autorizado para guardarse.');const group=$('itemGroup').value;const payload={trip_id:state.selectedTrip.id,bag_id:$('itemBag').value||null,user_id:state.user.id,catalog_item_id:verification?.product?.id||null,custom_name:verification?.product?.id?null:name,quantity:Number($('itemQuantity').value)||1,unit:$('itemUnit').value||'unidad',item_group:group,regulatory_required:requires,packed:false,packing_notes:$('itemNotes').value.trim()||null,homemade:requires?$('itemHomemade').checked:null,cooked_state:requires?$('itemCooked').value:'not_applicable',commercial_packaging:requires?$('itemCommercial').checked:null,hermetically_sealed:requires?$('itemSealed').checked:null,shelf_stable:requires?$('itemShelfStable').checked:null,contains_meat:requires?$('itemContainsMeat').checked:null,computed_decision:verification?.decision||'allowed',computed_risk:verification?.riskLevel||'low',matched_rule_id:verification?.matchedRuleId||null,rule_version:verification?.ruleVersion||null,verification_id:verification?.verificationId||null,declared:false};const r=await supabase.from('trip_items').insert(payload);if(r.error)throw r.error;closeDialog('itemDialog');await loadTripData(state.selectedTrip.id);renderDashboard();renderPacking();showToast(requires?'Artículo verificado y agregado.':'Artículo agregado a tu checklist.','success');}

async function addBag(e){e.preventDefault();const payload={trip_id:state.selectedTrip.id,user_id:state.user.id,bag_type:$('bagType').value,label:$('bagName').value.trim(),weight_kg:$('bagWeight').value?Number($('bagWeight').value):null};const r=await supabase.from('trip_bags').insert(payload);if(r.error)throw r.error;closeDialog('bagDialog');await loadTripData(state.selectedTrip.id);renderPacking();showToast('Maleta agregada.','success');}
function openMoveDialog(id){state.moveItemId=id;$('moveBagSelect').innerHTML='<option value="">Sin asignar</option>'+state.bags.map(b=>`<option value="${b.id}">${esc(b.label)} · ${esc(bagLabel(b.bag_type))}</option>`).join('');const item=state.items.find(i=>i.id===id);$('moveBagSelect').value=item?.bag_id||'';openDialog('moveDialog');}
async function moveItem(e){e.preventDefault();const r=await supabase.from('trip_items').update({bag_id:$('moveBagSelect').value||null}).eq('id',state.moveItemId).eq('user_id',state.user.id);if(r.error)throw r.error;closeDialog('moveDialog');await loadTripData(state.selectedTrip.id);renderPacking();}
async function togglePacked(id){const item=state.items.find(i=>i.id===id);if(!item)return;const r=await supabase.from('trip_items').update({packed:!item.packed}).eq('id',id).eq('user_id',state.user.id);if(r.error)throw r.error;await loadTripData(state.selectedTrip.id);renderDashboard();renderPackingContent();}
async function toggleDeclared(id){const item=state.items.find(i=>i.id===id);if(!item)return;const r=await supabase.from('trip_items').update({declared:!item.declared}).eq('id',id).eq('user_id',state.user.id);if(r.error)throw r.error;await loadTripData(state.selectedTrip.id);renderDashboard();renderPackingContent();}
async function deleteItem(id){if(!confirm('¿Eliminar este artículo de tu lista?'))return;const r=await supabase.from('trip_items').delete().eq('id',id).eq('user_id',state.user.id);if(r.error)throw r.error;await loadTripData(state.selectedTrip.id);renderDashboard();renderPackingContent();}

async function addDocument(e){e.preventDefault();let storagePath=null;const file=$('docFile').files?.[0];if(file){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');storagePath=`${state.user.id}/${state.selectedTrip.id}/${crypto.randomUUID()}-${safe}`;const up=await supabase.storage.from('travel-documents').upload(storagePath,file,{upsert:false});if(up.error)throw up.error;}const r=await supabase.from('trip_documents').insert({trip_id:state.selectedTrip.id,user_id:state.user.id,document_type:$('docType').value,masked_identifier:$('docMasked').value.trim()||null,expires_on:$('docExpiry').value||null,storage_path:storagePath});if(r.error)throw r.error;closeDialog('documentDialog');await loadTripData(state.selectedTrip.id);renderDashboard();renderDocuments();showToast('Documento guardado.','success');}
async function deleteDocument(id){if(!confirm('¿Eliminar este registro de documento?'))return;const r=await supabase.from('trip_documents').delete().eq('id',id).eq('user_id',state.user.id);if(r.error)throw r.error;await loadTripData(state.selectedTrip.id);renderDocuments();}
async function saveSnapshot(){const s=currentScores();const r=await supabase.from('compliance_snapshots').insert({trip_id:state.selectedTrip.id,user_id:state.user.id,document_score:s.docs,stay_score:100,cbp_score:s.regulatory,usda_score:s.regulatory,tsa_score:0,readiness_score:s.readiness,blockers:s.blockers.map(i=>({level:i.computed_risk,text:itemName(i)}))});if(r.error)throw r.error;showToast('Balance guardado en el historial.','success');}
async function completeTrip(){const r=await supabase.from('trips').update({status:'completed'}).eq('id',state.selectedTrip.id).eq('user_id',state.user.id);if(r.error)throw r.error;await loadTrips();await loadTripData(state.selectedTrip.id);renderDashboard();renderPacking();showToast('Viaje marcado como completado.','success');}

async function signIn(e){e.preventDefault();const r=await supabase.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});if(r.error)throw r.error;if(r.data.session)await authenticated(r.data.session);}
async function signUp(){const email=$('loginEmail').value.trim(),password=$('loginPassword').value;if(!email||password.length<8)throw new Error('Usa un correo válido y una contraseña de al menos 8 caracteres.');const redirect=`${window.location.origin}${window.location.pathname}`;const r=await supabase.auth.signUp({email,password,options:{emailRedirectTo:redirect}});if(r.error)throw r.error;if(r.data.session)await authenticated(r.data.session);else showToast('Cuenta creada. Revisa tu correo para confirmar el acceso.','success');}
async function forgot(){const email=$('loginEmail').value.trim();if(!email)throw new Error('Escribe tu correo primero.');const r=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}${window.location.pathname}`});if(r.error)throw r.error;showToast('Enlace de recuperación enviado.','success');}
async function signOut(){await supabase.auth.signOut();signedOut();}
function signedOut(){state.session=null;state.user=null;state.profile=null;state.isAdmin=false;$('authView').classList.remove('hidden');$('appView').classList.add('hidden');}
async function authenticated(session){state.session=session;state.user=session.user;$('authView').classList.add('hidden');$('appView').classList.remove('hidden');await loadBase();$('avatarInitials').textContent=initials();$('adminNav').classList.toggle('hidden',!state.isAdmin);$('mobileProfileLabel').textContent=state.isAdmin?'Admin':'Perfil';renderDashboard();renderTrips();renderPacking();renderDocuments();renderCatalog();renderProfile();setView('dashboard');}

function bindStatic(){document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>closeDialog(b.dataset.close)));$('loginForm').addEventListener('submit',e=>signIn(e).catch(handleError));$('signupBtn').addEventListener('click',()=>signUp().catch(handleError));$('forgotBtn').addEventListener('click',()=>forgot().catch(handleError));$('togglePassword').addEventListener('click',()=>{$('loginPassword').type=$('loginPassword').type==='password'?'text':'password';});$('tripForm').addEventListener('submit',e=>createTrip(e).catch(handleError));$('itemForm').addEventListener('submit',e=>handleItemSubmit(e).catch(handleError));$('itemGroup').addEventListener('change',()=>{state.itemVerification=null;$('verificationBox').className='verification hidden';updateRegulatoryFields();});$('itemForm').addEventListener('input',()=>{state.itemVerification=null;$('verificationBox').className='verification hidden';});$('bagForm').addEventListener('submit',e=>addBag(e).catch(handleError));$('moveForm').addEventListener('submit',e=>moveItem(e).catch(handleError));$('documentForm').addEventListener('submit',e=>addDocument(e).catch(handleError));$('globalAdd').addEventListener('click',()=>state.selectedTrip?openItemWizard():openTripWizard());$('profileButton').addEventListener('click',()=>setView(state.isAdmin?'admin':'profile'));bindNav(document);}

async function boot(){bindStatic();const r=await supabase.auth.getSession();if(r.data?.session)await authenticated(r.data.session).catch(handleError);else signedOut();supabase.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT')signedOut();else if(session&&!state.session)setTimeout(()=>authenticated(session).catch(handleError),0);});if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));}

boot().catch(handleError);
